<?php

namespace Database\Seeders;

use App\Models\JobRole;
use Illuminate\Database\Seeder;

class JobRolesSeeder extends Seeder
{
    public function run(): void
    {
        $roles = [
            'Accountant', 'Academic Advisor', 'Academic Coach', 'Actor',
            'Administrative Assistant', 'Administrative Coordinator', 'Administrative Manager',
            'Administrative Specialist', 'Admissions Counselor', 'Advertising Manager',
            'Aerospace Engineer', 'Affiliate Marketing Manager', 'Agile Coach',
            'Agricultural Engineer', 'Agricultural Scientist', 'Agronomist',
            'AI Consultant', 'AI Engineer', 'AI Researcher', 'Air Traffic Controller',
            'Animal Control Officer', 'Animal Geneticist', 'Animal Nutritionist',
            'Animal Trainer', 'Animator', 'Anesthesiologist', 'Anthropologist',
            'Aquatic Ecologist', 'Arbitrator', 'Architect', 'Art Director',
            'Asset Manager', 'Astronomer', 'Atmospheric Scientist', 'Attorney',
            'Auditor', 'Automation Engineer', 'Automotive Technician',
            'Background Investigator', 'Barber', 'Barista', 'Bartender',
            'Beautician', 'Beekeeper', 'Benefits Advisor', 'Benefits Manager',
            'BIM Manager', 'Biochemist', 'Biomedical Engineer', 'Biomedical Researcher',
            'Biostatistician', 'Biologist', 'Blockchain Developer', 'Blogger',
            'Boilermaker', 'Bookkeeper', 'Border Patrol Agent', 'Brand Ambassador',
            'Brand Designer', 'Brand Manager', 'Bricklayer', 'Budget Analyst',
            'Building Inspector', 'Bus Driver', 'Business Analyst', 'Business Consultant',
            'Business Development Manager', 'Business Development Representative',
            'Business Intelligence Analyst', 'Business Operations Manager', 'Buyer',
            'Cabinet Maker', 'Call Center Agent', 'Call Center Manager', 'Cardiologist',
            'Caregiver', 'Carpenter', 'Case Manager', 'Casino Dealer', 'Category Manager',
            'Catering Manager', 'Change Management Consultant', 'Charge Nurse', 'Chauffeur',
            'Chemical Engineer', 'Chemist', 'Chief Compliance Officer',
            'Chief Customer Officer', 'Chief Data Officer', 'Chief Diversity Officer',
            'Chief Executive Officer', 'Chief Financial Officer',
            'Chief Information Officer', 'Chief Information Security Officer',
            'Chief Legal Officer', 'Chief Marketing Officer', 'Chief Medical Officer',
            'Chief Nursing Officer', 'Chief of Staff', 'Chief Operating Officer',
            'Chief People Officer', 'Chief Product Officer', 'Chief Revenue Officer',
            'Chief Sales Officer', 'Chief Technology Officer', 'City Manager',
            'City Planner', 'Civil Engineer', 'Claims Adjuster', 'Clinical Manager',
            'Clinical Nurse Specialist', 'Clinical Research Associate',
            'Clinical Research Coordinator', 'Closing Coordinator', 'Cloud Architect',
            'Cloud Engineer', 'Co-Founder', 'Collections Specialist', 'Columnist',
            'Commissioning Engineer', 'Community Manager', 'Community Outreach Coordinator',
            'Compensation Analyst', 'Compliance Analyst', 'Compliance Manager',
            'Compliance Officer', 'Computer Vision Engineer', 'Concierge',
            'Conservation Scientist', 'Conservationist', 'Construction Estimator',
            'Construction Manager', 'Content Marketing Manager', 'Content Producer',
            'Content Strategist', 'Content Writer', 'Contract Administrator',
            'Controls Engineer', 'Copywriter', 'Corporate Attorney', 'Corporate Trainer',
            'Corrections Officer', 'Cost Accountant', 'Cosmetologist',
            'Cosmetology Instructor', 'Courier', 'Court Clerk', 'Court Reporter',
            'Crane Operator', 'Creative Director', 'Creative Strategist', 'Credit Analyst',
            'Cruise Director', 'Curriculum Developer', 'Customs Broker',
            'Customs Inspector', 'Cybersecurity Analyst', 'Data Analyst',
            'Data Annotator', 'Data Architect', 'Data Engineer', 'Data Entry Clerk',
            'Data Scientist', 'Database Administrator', 'Dean', 'Demand Generation Manager',
            'Dental Assistant', 'Dental Hygienist', 'Dentist', 'Department Chair',
            'Dermatologist', 'Design Engineer', 'Detective', 'DevOps Engineer',
            'Dietitian', 'Digital Marketing Specialist', 'Diplomat',
            'Director of Operations', 'Dispatcher', 'Distribution Manager',
            'Diversity and Inclusion Specialist', 'Drywall Installer',
            'E-commerce Manager', 'Ecologist', 'Economist', 'Editor', 'Editor-in-Chief',
            'Electrician', 'Electrologist', 'Elevator Technician',
            'Email Marketing Specialist', 'Embedded Systems Engineer', 'EMT',
            'Energy Analyst', 'Energy Engineer', 'Energy Manager', 'Enterprise Architect',
            'Entrepreneur', 'Environmental Consultant', 'Environmental Engineer',
            'Environmental Scientist', 'Epidemiologist', 'ERP Consultant', 'ESL Teacher',
            'Esthetician', 'Event Planner', 'Executive Assistant', 'Executive Chef',
            'Executive Director', 'Facilities Manager', 'Family Nurse Practitioner',
            'Farmer', 'Fashion Designer', 'Field Engineer', 'Field Marketing Representative',
            'Film Director', 'Film Critic', 'Financial Advisor', 'Financial Analyst',
            'Financial Planner', 'Firefighter', 'Firmware Engineer', 'Fitness Coach',
            'Fleet Manager', 'Flight Attendant', 'Food Scientist',
            'Foreign Service Officer', 'Forensic Accountant', 'Forester', 'Founder',
            'Freight Forwarder', 'Front Desk Agent', 'Frontend Developer',
            'Full-Stack Developer', 'Fundraiser', 'Game Developer', 'General Contractor',
            'General Counsel', 'General Manager', 'Genetic Counselor', 'Geneticist',
            'Geologist', 'Geotechnical Engineer', 'Geriatric Care Manager',
            'Ghostwriter', 'Glazier', 'Grant Writer', 'Graphic Designer',
            'Growth Marketer', 'Hair Stylist', 'Healthcare Administrator',
            'Health Data Analyst', 'Health Educator', 'Health Information Manager',
            'Heavy Equipment Operator', 'Help Desk Technician', 'Home Health Aide',
            'Horticulturist', 'Hospital Administrator', 'Hotel Manager', 'Housekeeper',
            'HR Analyst', 'HR Assistant', 'HR Business Partner', 'HR Coordinator',
            'HR Generalist', 'HR Manager', 'HVAC Engineer', 'HVAC Technician',
            'Illustrator', 'Import/Export Specialist', 'Industrial Designer',
            'Industrial Engineer', 'Infection Control Specialist',
            'Influencer Marketing Manager', 'Instructional Designer', 'Insurance Agent',
            'Insurance Broker', 'Insurance Underwriter', 'Intelligence Analyst',
            'Interior Designer', 'Investment Analyst', 'Investment Banker',
            'iOS Developer', 'IT Analyst', 'IT Consultant', 'IT Director', 'IT Manager',
            'IT Project Manager', 'IT Support Specialist', 'Java Developer',
            'Journalist', 'Judge', 'Kennel Manager', 'Kitchen Manager', 'Lab Manager',
            'Lab Technician', 'Landscape Architect', 'Landscaper', 'Law Clerk',
            'Lawyer', 'Leasing Consultant', 'Learning and Development Manager',
            'Legal Assistant', 'Legal Researcher', 'Legal Secretary',
            'Legislative Assistant', 'Librarian', 'Licensed Practical Nurse',
            'Litigation Attorney', 'Lobbyist', 'Locksmith', 'Logistics Coordinator',
            'Logistics Manager', 'Loss Prevention Specialist', 'Machine Operator',
            'Machinist', 'Mail Carrier', 'Maintenance Technician', 'Makeup Artist',
            'Management Consultant', 'Managing Director', 'Managing Editor',
            'Manufacturing Engineer', 'Marine Engineer', 'Market Research Analyst',
            'Marketing Analyst', 'Marketing Coordinator', 'Marketing Director',
            'Marketing Manager', 'Marketing Operations Manager', 'Marketing Strategist',
            'Mason', 'Massage Therapist', 'Materials Engineer', 'Materials Scientist',
            'Media Buyer', 'Media Planner', 'Medical Biller', 'Medical Coder',
            'Medical Director', 'Medical Lab Technician', 'Medical Social Worker',
            'Medical Transcriptionist', 'Mediator', 'Mental Health Counselor',
            'Merchandise Planner', 'Microbiologist', 'Military Officer',
            'Mining Engineer', 'MLOps Engineer', 'Mobile Developer',
            'Motion Graphics Designer', 'Music Producer', 'Nail Technician',
            'Network Administrator', 'Network Engineer', 'Neurologist', 'NLP Engineer',
            'Nonprofit Accountant', 'Nuclear Engineer', 'Nurse Practitioner',
            'Nutritionist', 'Occupational Therapist', 'Oceanographer', 'Office Manager',
            'Oncologist', 'Online Course Developer', 'Operations Analyst',
            'Operations Coordinator', 'Operations Manager', 'Ophthalmologist',
            'Optometrist', 'Oral Surgeon', 'Organizational Development Specialist',
            'Orthodontist', 'Orthopedic Surgeon', 'Paralegal', 'Paramedic',
            'Patent Agent', 'Patient Care Technician', 'Payroll Specialist',
            'Pediatrician', 'Penetration Tester', 'Personal Assistant',
            'Personal Shopper', 'Personal Trainer', 'Petroleum Engineer', 'Pharmacist',
            'Pharmacy Technician', 'Phlebotomist', 'Photographer', 'Physical Therapist',
            'Physician', 'Physician Assistant', 'Physicist', 'Pilot', 'Pipefitter',
            'Plant Manager', 'Platform Engineer', 'Plumber', 'Podcaster',
            'Police Officer', 'Policy Analyst', 'Political Scientist',
            'Population Health Manager', 'Portfolio Manager', 'Postdoctoral Fellow',
            'Power Plant Operator', 'Principal Architect', 'Principal Investigator',
            'Principal', 'Probation Officer', 'Process Engineer',
            'Process Improvement Manager', 'Procurement Manager',
            'Procurement Specialist', 'Producer', 'Product Designer', 'Product Engineer',
            'Product Manager', 'Product Marketing Manager', 'Production Manager',
            'Production Planner', 'Production Supervisor', 'Program Analyst',
            'Program Coordinator', 'Program Manager', 'Project Engineer',
            'Project Manager', 'Property Manager', 'Proposal Writer',
            'Psychiatric Nurse Practitioner', 'Psychiatrist', 'Psychologist',
            'Public Affairs Specialist', 'Public Defender', 'Public Health Specialist',
            'Public Relations Manager', 'Public Relations Specialist', 'Publicist',
            'Purchasing Manager', 'Python Developer', 'QA Engineer',
            'Quality Control Inspector', 'Quality Engineer', 'Quantitative Analyst',
            'Radiologic Technologist', 'Radiologist', 'Real Estate Agent',
            'Real Estate Analyst', 'Real Estate Appraiser', 'Real Estate Broker',
            'Real Estate Developer', 'Receptionist', 'Records Manager', 'Recruiter',
            'Registered Nurse', 'Regulatory Affairs Specialist', 'Reliability Engineer',
            'Renewable Energy Technician', 'Reporter', 'Research Scientist',
            'Research Assistant', 'Restaurant Manager', 'Retail Manager',
            'Risk Analyst', 'Risk Manager', 'Robotics Engineer', 'Roofer',
            'Safety Engineer', 'Safety Manager', 'Salesforce Developer',
            'SAP Consultant', 'School Bus Driver', 'School Counselor', 'Screenwriter',
            'Scrum Master', 'Secretary', 'Security Architect', 'Security Engineer',
            'SEO Specialist', 'Server', 'Sheet Metal Worker', 'Ship Captain',
            'Site Reliability Engineer', 'Social Media Manager', 'Social Media Specialist',
            'Social Services Manager', 'Social Worker', 'Sociologist',
            'Solar Energy Specialist', 'Solar Engineer', 'Sommelier', 'SOC Analyst',
            'Sound Engineer', 'Sous Chef', 'Special Education Teacher',
            'Speech-Language Pathologist', 'Speechwriter', 'SQL Developer',
            'Startup Advisor', 'Statistician', 'Store Manager', 'Strategy Consultant',
            'Structural Engineer', 'Substance Abuse Counselor', 'Superintendent',
            'Supply Chain Analyst', 'Supply Chain Manager', 'Supply Planner', 'Surgeon',
            'Surgical Technologist', 'Sustainability Consultant', 'Sustainability Manager',
            'Systems Administrator', 'Systems Analyst', 'Systems Engineer',
            'Talent Acquisition Specialist', 'Talent Manager', 'Tax Accountant',
            'Tax Manager', 'Teacher', 'Teaching Assistant', 'Technical Product Manager',
            'Technical Support Specialist', 'Technical Writer',
            'Telemedicine Coordinator', 'Territory Sales Manager', 'Train Conductor',
            'Training Manager', 'Training Specialist', 'Transaction Coordinator',
            'Translator', 'Transportation Manager', 'Transportation Safety Manager',
            'Travel Agent', 'Travel Nurse', 'Treasurer', 'Truck Driver', 'Tutor',
            'UI Designer', 'Ultrasound Technician', 'Urban Planner', 'UX Designer',
            'UX Researcher', 'Venture Partner', 'Veterinarian', 'Veterinary Assistant',
            'Veterinary Technician', 'Video Editor', 'Videographer', 'Virtual Assistant',
            'Visual Designer', 'Visual Merchandiser', 'Volunteer Coordinator',
            'Warehouse Manager', 'Web Developer', 'Web Designer', 'Welder',
            'Wellness Coach', 'Wildlife Biologist', 'Wildlife Inspector',
            'Wildlife Rehabilitator', 'Wind Turbine Technician',
            'Workforce Planning Analyst', 'Youth Mentor', 'Yoga Instructor', 'Zoologist',
            'Android Developer', 'Backend Developer', 'Benefits Coordinator',
            'Brand Strategist', 'Business Process Analyst', 'Certified Nursing Assistant',
            'Clinical Nurse Leader', 'Communications Specialist',
            'Community Outreach Manager', 'Compliance Engineer', 'Computer Programmer',
            'Construction Worker', 'Contact Center Supervisor', 'Content Creator',
            'Controller', 'Corporate Communications Manager', 'Corporate Lawyer',
            'Customer Experience Manager', 'Customer Service Manager',
            'Customer Service Representative', 'Customer Success Manager',
            'Cybersecurity Manager', 'Database Architect', 'Development Director',
            'Digital Forensics Analyst', 'Director of Business Development',
            'District Manager', 'eCommerce Specialist', 'Employee Relations Specialist',
            'Enterprise Sales Manager', 'Environmental Manager', 'Equity Analyst',
            'Executive Recruiter', 'Field Engineer', 'Financial Services Representative',
            'Fleet Coordinator', 'Food and Beverage Manager', 'Front-End Developer',
            'Grant Manager', 'Growth Hacker', 'HR Operations Manager', 'HRIS Analyst',
            'Healthcare Reimbursement Specialist', 'Hotel Front Desk Clerk',
            'Human Resources Director', 'Industrial Hygienist',
            'Information Security Analyst', 'Inside Sales Representative',
            'Instructional Coach', 'Insurance Investigator', 'Insurance Sales Manager',
            'Intellectual Property Attorney', 'Inventory Control Specialist',
            'Inventory Manager', 'Key Account Manager', 'Lab Coordinator',
            'Land Surveyor', 'Landscape Designer', 'Learning Experience Designer',
            'Legal Analyst', 'Licensed Clinical Social Worker',
            'Loss Prevention Manager', 'Machine Learning Engineer',
            'Mechanical Designer', 'Media Relations Specialist', 'Medical Writer',
            'Membership Coordinator', 'Mobile Application Developer',
            'Mortgage Loan Officer', 'National Account Manager', 'National Sales Manager',
            'Network Security Engineer', 'Nurse Educator', 'Nurse Manager',
            'Occupational Health Specialist', 'Office Administrator',
            'Onboarding Specialist', 'Operations Director', 'Outside Sales Representative',
            'Pastry Chef', 'Patient Advocate', 'Payroll Manager',
            'People Operations Manager', 'Performance Marketing Manager',
            'Physical Therapy Assistant', 'Planning Manager', 'Plant Engineer',
            'Podcast Producer', 'Policy Manager', 'Portfolio Analyst', 'Practice Manager',
            'Preschool Teacher', 'Principal Engineer', 'Product Owner',
            'Production Worker', 'Program Director', 'Project Architect',
            'Proposal Manager', 'Public Information Officer', 'Purchasing Agent',
            'Quality Assurance Manager', 'Quality Assurance Specialist',
            'Quantitative Researcher', 'Real Estate Paralegal', 'Regional Sales Manager',
            'Regional Manager', 'Regulatory Compliance Manager', 'Relationship Manager',
            'Remote Sensing Analyst', 'Research Associate', 'Resort Activities Coordinator',
            'Retail Buyer', 'Retail Operations Manager', 'Revenue Analyst',
            'Revenue Manager', 'Sales Development Representative', 'Sales Engineer',
            'Sales Operations Manager', 'Service Delivery Manager',
            'Social Media Coordinator', 'Software Architect', 'Solutions Architect',
            'Solutions Consultant', 'Spa Manager', 'Staff Accountant',
            'Staffing Coordinator', 'Strategic Advisor', 'Strategic Partnerships Manager',
            'Structural Drafter', 'Student Advisor', 'Subcontractor',
            'Substitute Teacher', 'Supply Chain Director', 'Survey Researcher',
            'Tax Consultant', 'Technical Account Manager', 'Technical Project Manager',
            'Technical Recruiter', 'Test Engineer', 'Tour Guide Manager',
            'Trade Compliance Specialist', 'Trade Show Coordinator',
            'Training Coordinator', 'Transportation Coordinator', 'Travel Coordinator',
            'UI/UX Designer', 'Underwriter', 'User Researcher', 'Vendor Manager',
            'Venture Capitalist', 'Veterinary Pathologist', 'Virtual Call Center Agent',
            'Warehouse Supervisor', 'Web Administrator', 'Wellness Director',
            'Workers Compensation Specialist', 'Workforce Analyst',
            'Zoning Administrator',
        ];

        $records = array_map(fn ($title) => ['title' => $title], $roles);

        foreach (array_chunk($records, 100) as $chunk) {
            JobRole::upsert($chunk, ['title'], []);
        }
    }
}
