<?php

namespace Database\Seeders;

use App\Models\JobTitle;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JobTitlesSeeder extends Seeder
{
    private const EXTRAS_FILE = 'data/job_titles_extras.json';

    public function run(): void
    {
        $static = $this->staticTitles();

        // Persist any runtime-added rows to the extras file before a migration wipes the table.
        $extrasFile = database_path(self::EXTRAS_FILE);
        $savedExtras = file_exists($extrasFile) ? json_decode(file_get_contents($extrasFile), true) : [];

        try {
            $dbTitles = DB::table('job_titles')->pluck('title')->toArray();
            $newExtras = array_diff($dbTitles, $static);
            $savedExtras = array_values(array_unique(array_merge($savedExtras, $newExtras)));
            if (! is_dir(database_path('data'))) {
                mkdir(database_path('data'), 0755, true);
            }
            file_put_contents($extrasFile, json_encode($savedExtras, JSON_PRETTY_PRINT));
        } catch (\Exception) {
            // Table doesn't exist yet — fall through to saved extras only.
        }

        $all = array_unique(array_merge($static, $savedExtras));
        sort($all);
        $records = array_map(fn ($title) => ['title' => $title], $all);

        foreach (array_chunk($records, 100) as $chunk) {
            JobTitle::insertOrIgnore($chunk);
        }
    }

    /** @return string[] */
    private function staticTitles(): array
    {
        return [
            'Accounting Assistant', 'Accounting Clerk', 'Accounting Director',
            'Accounting Manager', 'Acquisitions Manager', 'Administrative Analyst',
            'Administrative Assistant', 'Administrative Coordinator',
            'Administrative Manager', 'Administrative Officer', 'Administrative Specialist',
            'Admissions Counselor', 'Advertising Manager', 'Advocacy Director',
            'Advocacy Specialist', 'Agile Coach', 'AI Engineer', 'AI Research Scientist',
            'AI Strategist', 'Android Developer', 'Anesthesiologist',
            'Animal Control Officer', 'Animal Shelter Manager', 'Animal Trainer',
            'Animator', 'Application Developer', 'Application Security Engineer',
            'Apprentice Carpenter', 'Apprentice Electrician', 'Apprentice Plumber',
            'Area Sales Manager', 'Art Director', 'Associate Attorney', 'Associate Dean',
            'Associate General Counsel', 'Associate Product Manager',
            'Associate Professor', 'Astronomer', 'Atmospheric Scientist', 'Audit Manager',
            'Auditor', 'Automation Engineer', 'Automotive Technician',
            'AWS Cloud Architect', 'Backend Developer', 'Banquet Chef', 'Banquet Manager',
            'Banquet Server', 'Barber', 'Barista', 'Bartender', 'Beautician',
            'Benefits Advisor', 'Benefits Manager', 'Beverage Director', 'BI Developer',
            'BIM Manager', 'Biomedical Engineer', 'Biostatistician',
            'Blockchain Consultant', 'Blockchain Developer', 'Blockchain Project Manager',
            'Bookkeeper', 'Branch Manager', 'Brand Ambassador', 'Brand Designer',
            'Brand Manager', 'Budget Analyst', 'Building Inspector', 'Business Analyst',
            'Business Development Executive', 'Business Development Manager',
            'Business Development Representative', 'Business Intelligence Analyst',
            'Business Manager', 'Business Operations Manager',
            'C-Suite Executive Assistant', 'Call Center Agent', 'Call Center Director',
            'Call Center Manager', 'Call Center Supervisor', 'Call Center Trainer',
            'Captain (Aviation)', 'Cardiologist', 'Caregiver', 'Carpenter',
            'Case Manager', 'Casino Dealer', 'Casino Host', 'Catering Manager',
            'CDL Truck Driver', 'Certified Nursing Assistant', 'Certified Welder',
            'Charge Nurse', 'Chief Accounting Officer', 'Chief Clinical Officer',
            'Chief Compliance Officer', 'Chief Culture Officer', 'Chief Customer Officer',
            'Chief Data Officer', 'Chief Diversity Officer', 'Chief Engineer',
            'Chief Executive Officer', 'Chief Financial Officer',
            'Chief Human Resources Officer', 'Chief Information Officer',
            'Chief Information Security Officer', 'Chief Legal Officer',
            'Chief Marketing Officer', 'Chief Medical Officer', 'Chief Nursing Officer',
            'Chief of Staff', 'Chief of Surgery', 'Chief Operating Officer',
            'Chief People Officer', 'Chief Product Officer', 'Chief Revenue Officer',
            'Chief Sales Officer', 'Chief Secretary', 'Chief Technology Officer',
            'City Manager', 'Civil Engineer', 'Claims Adjuster', 'Clinical Coordinator',
            'Clinical Manager', 'Clinical Nurse Leader', 'Clinical Nurse Specialist',
            'Clinical Research Associate', 'Clinical Research Coordinator',
            'Cloud Architect', 'Cloud Engineer', 'Cloud Security Specialist',
            'Cloud Solutions Architect', 'CNC Machinist', 'Collections Specialist',
            'Commissioning Manager', 'Communications Coordinator',
            'Communications Director', 'Communications Manager',
            'Communications Specialist', 'Community Development Manager',
            'Community Manager', 'Community Outreach Coordinator',
            'Community Outreach Manager', 'Community Support Specialist',
            'Compensation Analyst', 'Compensation and Benefits Manager',
            'Compliance Analyst', 'Compliance Manager', 'Compliance Officer',
            'Computer Programmer', 'Computer Scientist', 'Computer Vision Engineer',
            'Concierge', 'Concierge Supervisor', 'Conservation Scientist',
            'Construction Estimator', 'Construction Foreman', 'Construction Manager',
            'Construction Project Manager', 'Construction Project Lead',
            'Construction Scheduler', 'Construction Safety Manager',
            'Construction Worker', 'Contact Center Supervisor', 'Content Creator',
            'Content Marketing Manager', 'Content Marketing Specialist',
            'Content Producer', 'Content Strategist', 'Content Strategy Manager',
            'Content Writer', 'Contract Administrator', 'Contract Manager',
            'Controller', 'Controls Engineer', 'Cook', 'Copy Editor', 'Copywriter',
            'Corporate Attorney', 'Corporate Trainer', 'Corrections Officer',
            'Cost Accountant', 'Cosmetologist', 'Cosmetology Instructor',
            'Court Reporter', 'CPA', 'Crane Operator', 'Creative Director',
            'Creative Strategist', 'Credit Analyst', 'Credit Counselor',
            'Cruise Director', 'Customer Care Associate', 'Customer Care Representative',
            'Customer Care Specialist', 'Customer Engagement Manager',
            'Customer Experience Analyst', 'Customer Experience Manager',
            'Customer Operations Manager', 'Customer Retention Specialist',
            'Customer Service Manager', 'Customer Service Representative',
            'Customer Service Trainer', 'Customer Success Associate',
            'Customer Success Director', 'Customer Success Manager',
            'Cybersecurity Analyst', 'Cybersecurity Engineer', 'Cybersecurity Manager',
            'Data Annotator', 'Data Architect', 'Data Engineer', 'Data Entry Clerk',
            'Data Scientist', 'Database Administrator', 'Dean',
            'Demand Generation Manager', 'Department Chair', 'Department Manager',
            'Deputy General Counsel', 'Dermatologist', 'Design Lead',
            'Desktop Support Technician', 'Detective', 'Development Director',
            'DevOps Engineer', 'Dietitian', 'Digital Communication Coordinator',
            'Digital Content Producer', 'Digital Forensic Examiner',
            'Digital Marketing Manager', 'Digital Marketing Specialist',
            'Director of Architecture', 'Director of Business Development',
            'Director of Compliance', 'Director of Customer Service',
            'Director of Diversity and Inclusion', 'Director of Engineering',
            'Director of Events', 'Director of Facilities Management',
            'Director of Finance', 'Director of HR', 'Director of IT',
            'Director of Maintenance', 'Director of Marketing', 'Director of Nursing',
            'Director of Operations', 'Director of Philanthropy',
            'Director of Product Management', 'Director of Program Management',
            'Director of Security', 'Director of Supply Chain', 'Dispatcher',
            'District Manager', 'Diversity and Inclusion Manager',
            'Diversity and Inclusion Specialist', 'Diversity Consultant',
            'Diversity Coordinator', 'Diversity Director', 'Diversity Officer',
            'Doctor', 'Drywall Installer', 'E-commerce Manager', 'Economist',
            'Editor', 'Editor-in-Chief', 'Education Administrator',
            'Education Coordinator', 'Electrical Engineer', 'Electrician',
            'Email Marketing Manager', 'Email Marketing Specialist',
            'Embedded Systems Engineer', 'EMT', 'Employee Experience Manager',
            'Employee Relations Manager', 'Employee Relations Specialist',
            'Energy Analyst', 'Energy Engineer', 'Energy Manager',
            'Engineering Manager', 'Engineering Technician',
            'Enterprise Account Executive', 'Enterprise Architect',
            'Enterprise Sales Executive', 'Environmental Artist',
            'Environmental Engineer', 'Environmental Manager', 'Environmental Scientist',
            'Epidemiologist', 'ERP Consultant', 'Escalation Specialist', 'ESL Teacher',
            'Esthetician', 'Event Coordinator', 'Event Manager', 'Event Planner',
            'Executive Chef', 'Executive Director', 'Executive Assistant',
            'Executive Recruiter', 'Executive Secretary',
            'Executive Vice President of Operations', 'Facilities Assistant',
            'Facilities Coordinator', 'Facilities Engineer',
            'Facilities Maintenance Manager', 'Facilities Manager',
            'Family Nurse Practitioner', 'Fashion Designer', 'Field Engineer',
            'Field Marketing Representative', 'Field Sales Representative',
            'Finance Director', 'Finance Manager', 'Financial Advisor',
            'Financial Analyst', 'Financial Consultant', 'Financial Manager',
            'Financial Planner', 'Financial Services Representative',
            'Firmware Engineer', 'Flight Attendant', 'Food and Beverage Director',
            'Food and Beverage Manager', 'Food Runner', 'Forensic Accountant',
            'Founder', 'Franchise Development Manager', 'Freight Forwarder',
            'Front Desk Agent', 'Front Desk Manager', 'Front-End Developer',
            'Full-Stack Developer', 'Fundraising Manager', 'Game Designer',
            'Game Developer', 'Game Tester', 'Game Writer', 'General Contractor',
            'General Counsel', 'General Manager', 'Genetic Counselor', 'Geneticist',
            'Geologist', 'Geotechnical Engineer', 'Global Mobility Specialist',
            'Graduate Teaching Assistant', 'Grant Writer', 'Graphic Designer',
            'Growth Marketing Manager', 'Guest Relations Manager',
            'Guidance Counselor', 'Headhunter', 'Head of Customer Experience',
            'Head of Customer Success', 'Head of Design', 'Head of IT',
            'Head of Marketing', 'Health Data Analyst', 'Health Educator',
            'Health Information Manager', 'Health Information Technician',
            'Healthcare Administrator', 'Healthcare Operations Analyst',
            'Healthcare Reimbursement Specialist', 'Heavy Equipment Operator',
            'Help Desk Analyst', 'Help Desk Technician', 'Home Health Aide',
            'Hostess', 'Hotel Front Desk Clerk', 'Hotel Manager', 'HR Administrator',
            'HR Analyst', 'HR Assistant', 'HR Business Partner', 'HR Coordinator',
            'HR Director', 'HR Generalist', 'HR Manager', 'HR Operations Manager',
            'HR Payroll Administrator', 'HR Payroll Specialist', 'HR Specialist',
            'HRIS Analyst', 'HVAC Installer', 'HVAC Manager', 'HVAC Technician',
            'ICU Nurse', 'Illustrator', 'Implementation Manager',
            'Infection Control Specialist', 'Information Security Auditor',
            'Information Security Engineer', 'Information Security Manager',
            'Information Security Specialist', 'Instructional Coach',
            'Instructional Coordinator', 'Instructional Designer',
            'Insurance Adjuster', 'Insurance Agent', 'Insurance Analyst',
            'Insurance Broker', 'Insurance Investigator', 'Insurance Sales Manager',
            'Insurance Underwriter', 'Intelligence Analyst', 'Interior Designer',
            'Internal Auditor', 'Inventory Control Manager',
            'Inventory Control Specialist', 'Inventory Manager', 'iOS Developer',
            'IT Auditor', 'IT Director', 'IT Manager', 'IT Operations Manager',
            'IT Project Manager', 'IT Support Specialist', 'IT Trainer',
            'Java Developer', 'Java Software Engineer', 'Junior Accountant',
            'Junior Architect', 'Junior Financial Analyst', 'Junior Frontend Developer',
            'Junior Graphic Designer', 'Junior IT Engineer', 'Junior Product Manager',
            'Junior Software Engineer', 'Junior UX Designer', 'Key Account Manager',
            'Key Holder', 'Kitchen Manager', 'Lab Manager', 'Lab Technician',
            'Land Surveyor', 'Landscape Architect', 'Law Clerk', 'Lead Accountant',
            'Lead Data Analyst', 'Lead Data Engineer', 'Lead Frontend Developer',
            'Lead Full-Stack Developer', 'Lead Mechanical Engineer', 'Lead Nurse',
            'Lead Product Manager', 'Lead Recruiter', 'Lead Software Developer',
            'Lead UX Designer', 'Leasing Consultant', 'Leasing Manager',
            'Learning and Development Manager', 'Learning and Development Specialist',
            'Learning Consultant', 'Lecturer', 'Legal Administrator', 'Legal Analyst',
            'Legal Assistant', 'Legal Counsel', 'Legal Researcher', 'Legal Secretary',
            'Legal Supervisor', 'Legislative Assistant',
            'Licensed Clinical Social Worker', 'Licensed Massage Therapist',
            'Licensed Practical Nurse', 'Line Cook', 'Litigation Attorney',
            'Live Chat Agent', 'Lobbyist', 'Logistics Coordinator',
            'Logistics Engineer', 'Logistics Manager', 'Long-Haul Truck Driver',
            'Machine Learning Engineer', 'Machine Operator', 'Machinist',
            'Makeup Artist', 'Management Consultant', 'Managing Director',
            'Managing Editor', 'Manufacturing Engineer', 'Marine Engineer',
            'Market Development Manager', 'Market Research Analyst',
            'Marketing Analyst', 'Marketing Assistant', 'Marketing Coordinator',
            'Marketing Director', 'Marketing Manager', 'Marketing Operations Manager',
            'Marketing Research Analyst', 'Marketing Strategist', 'Mason',
            'Master Barber', 'Master Carpenter', 'Master Electrician',
            'Master Hair Stylist', 'Master Plumber', 'Materials Engineer',
            'Materials Manager', 'Materials Scientist', 'Media Buyer', 'Media Planner',
            'Media Relations Manager', 'Media Relations Specialist',
            'Medical Assistant', 'Medical Biller', 'Medical Coder', 'Medical Director',
            'Medical Lab Technician', 'Medical Researcher', 'Medical Scientist',
            'Medical Transcriptionist', 'Medical Writer', 'Membership Coordinator',
            'Mental Health Counselor', 'Merchandise Planner',
            'Merchandising Associate', 'Merchandising Manager', 'Microbiologist',
            'Military Officer', 'Mining Engineer', 'MLOps Engineer',
            'Mobile App Developer', 'Motion Graphics Designer', 'Mortgage Loan Officer',
            'Music Producer', 'Nail Technician', 'National Account Manager',
            'National Sales Director', 'National Sales Manager',
            'Network Administrator', 'Network Engineer', 'NLP Engineer',
            'Nonprofit Program Coordinator', 'Nonprofit Program Manager',
            'Nuclear Engineer', 'Nurse Clinician', 'Nurse Manager',
            'Nurse Practitioner', 'Nurse Supervisor', 'Nutritionist',
            'Occupational Therapist', 'Office Administrator', 'Office Clerk',
            'Office Coordinator', 'Office Manager', 'Onboarding Specialist',
            'Online Course Developer', 'Operations Analyst', 'Operations Assistant',
            'Operations Coordinator', 'Operations Director', 'Operations Manager',
            'Operations Research Analyst', 'Operations Specialist', 'Ophthalmologist',
            'Optometrist', 'Oral Surgeon', 'Orthodontist', 'Orthopedic Surgeon',
            'Outside Sales Manager', 'Outside Sales Representative',
            'Paid Media Specialist', 'Paralegal', 'Paramedic', 'Partner Attorney',
            'Pastry Chef', 'Patent Agent', 'Patient Care Technician',
            'Patient Experience Director', 'Payroll Accountant',
            'Payroll Administrator', 'Payroll Clerk', 'Payroll Director',
            'Payroll Manager', 'Payroll Processor', 'Payroll Specialist',
            'Payroll Technician', 'Pediatrician', 'Penetration Tester',
            'People Operations Manager', 'Performance Management Specialist',
            'Personal Assistant', 'Personal Trainer', 'Petroleum Engineer',
            'Pharmacist', 'Pharmacy Technician', 'Phlebotomist', 'Photographer',
            'Physical Therapist', 'Physical Therapy Assistant',
            'Physical Therapy Manager', 'Physician', 'Physician Assistant', 'Pilot',
            'Pipefitter', 'Plant Engineer', 'Plant Manager', 'Platform Engineer',
            'Plumber', 'PMO Manager', 'Podcaster', 'Police Captain', 'Police Officer',
            'Police Sergeant', 'Policy Analyst', 'Population Health Manager',
            'Portfolio Manager', 'Postdoctoral Fellow', 'Power Plant Operator',
            'Prep Cook', 'Preschool Teacher', 'Principal Architect',
            'Principal Engineer', 'Principal Investigator', 'Principal Product Manager',
            'Principal Research Scientist', 'Principal Software Engineer',
            'Probation Officer', 'Process Engineer', 'Process Improvement Manager',
            'Procurement Manager', 'Procurement Specialist', 'Product Analyst',
            'Product Designer', 'Product Engineer', 'Product Manager',
            'Product Marketing Manager', 'Product Owner', 'Production Artist',
            'Production Engineer', 'Production Manager', 'Production Planner',
            'Production Supervisor', 'Production Worker', 'Program Administrator',
            'Program Analyst', 'Program Coordinator', 'Program Director',
            'Program Manager', 'Project Architect', 'Project Engineer',
            'Project Manager', 'Property Manager', 'Proposal Writer',
            'Psychiatric Nurse Practitioner', 'Psychiatrist', 'Psychologist',
            'Public Affairs Manager', 'Public Affairs Specialist', 'Public Defender',
            'Public Health Nurse', 'Public Health Specialist',
            'Public Information Officer', 'Public Relations Assistant',
            'Public Relations Coordinator', 'Public Relations Director',
            'Public Relations Manager', 'Public Relations Specialist', 'Publicist',
            'Purchasing Agent', 'Purchasing Manager', 'Python Developer',
            'QA Manager', 'QA Tester', 'Quality Assurance Engineer',
            'Quality Assurance Manager', 'Quality Assurance Scientist',
            'Quality Assurance Specialist', 'Quality Assurance Team Leader',
            'Quality Control Inspector', 'Quality Control Manager', 'Quality Engineer',
            'Quantitative Analyst', 'Quantitative Researcher', 'Radiologic Technologist',
            'Radiologist', 'Real Estate Agent', 'Real Estate Analyst',
            'Real Estate Appraiser', 'Real Estate Broker', 'Real Estate Developer',
            'Real Estate Paralegal', 'Receptionist', 'Records Manager', 'Recruiter',
            'Regional Manager', 'Regional Retail Manager', 'Regional Sales Manager',
            'Registered Nurse', 'Registered Respiratory Therapist',
            'Regulatory Affairs Manager', 'Regulatory Affairs Specialist',
            'Relationship Manager', 'Reliability Engineer',
            'Renewable Energy Technician', 'Reporter',
            'Research and Development Manager', 'Research Assistant',
            'Research Associate', 'Research Coordinator', 'Research Director',
            'Research Scientist', 'Reservations Manager',
            'Resort Activities Coordinator', 'Restaurant Chain Executive',
            'Restaurant Manager', 'Retail Operations Manager', 'Revenue Manager',
            'Risk Analyst', 'Risk Manager', 'Robotics Engineer', 'Roofer',
            'Route Planner', 'Safety Engineer', 'Safety Manager',
            'Salesforce Developer', 'SAP Consultant', 'School Bus Driver',
            'School Counselor', 'Screenwriter', 'Scrum Master', 'Secretary',
            'Security Architect', 'Security Engineer', 'Senior Account Executive',
            'Senior Account Manager', 'Senior Accountant', 'Senior Architect',
            'Senior Attorney', 'Senior BI Analyst', 'Senior Business Analyst',
            'Senior Business Development Manager',
            'Senior Business Development Representative', 'Senior Cloud Architect',
            'Senior Cloud Engineer', 'Senior Communications Manager',
            'Senior Compensation Analyst', 'Senior Compliance Analyst',
            'Senior Compliance Officer', 'Senior Construction Estimator',
            'Senior Construction Manager', 'Senior Content Strategist',
            'Senior Content Writer', 'Senior Controller', 'Senior Copywriter',
            'Senior Credit Analyst', 'Senior Cybersecurity Analyst',
            'Senior Data Architect', 'Senior Data Scientist',
            'Senior Database Administrator', 'Senior Designer', 'Senior DevOps Engineer',
            'Senior Digital Marketing Specialist', 'Senior Engineer',
            'Senior Environmental Consultant', 'Senior Environmental Engineer',
            'Senior Financial Advisor', 'Senior Financial Analyst',
            'Senior Frontend Developer', 'Senior Full-Stack Developer',
            'Senior Game Developer', 'Senior HR Business Partner', 'Senior HR Manager',
            'Senior Illustrator', 'Senior Industrial Engineer',
            'Senior Instructional Designer', 'Senior Internal Auditor',
            'Senior Investment Analyst', 'Senior IT Manager', 'Senior IT Project Manager',
            'Senior IT Support Specialist', 'Senior Java Developer',
            'Senior Lab Technician', 'Senior Logistics Coordinator',
            'Senior Logistics Manager', 'Senior Machine Learning Engineer',
            'Senior Manufacturing Engineer', 'Senior Market Research Analyst',
            'Senior Marketing Analyst', 'Senior Marketing Manager',
            'Senior Mechanical Engineer', 'Senior Mobile Developer',
            'Senior Mortgage Loan Officer', 'Senior Network Engineer',
            'Senior Operations Analyst', 'Senior Operations Manager',
            'Senior Paralegal', 'Senior Payroll Specialist', 'Senior Physical Therapist',
            'Senior Physician', 'Senior Portfolio Manager', 'Senior Process Engineer',
            'Senior Procurement Manager', 'Senior Procurement Specialist',
            'Senior Product Analyst', 'Senior Product Manager',
            'Senior Product Marketing Manager', 'Senior Program Manager',
            'Senior Project Engineer', 'Senior Project Manager', 'Senior Python Developer',
            'Senior QA Engineer', 'Senior Quality Engineer',
            'Senior Quantitative Analyst', 'Senior Real Estate Agent',
            'Senior Real Estate Broker', 'Senior Recruiter',
            'Senior Regulatory Affairs Specialist', 'Senior Research Associate',
            'Senior Research Scientist', 'Senior Risk Analyst', 'Senior Sales Analyst',
            'Senior Sales Manager', 'Senior Sales Representative',
            'Senior Security Engineer', 'Senior SEO Specialist',
            'Senior Site Reliability Engineer', 'Senior Software Developer',
            'Senior Software Engineer', 'Senior Solutions Architect',
            'Senior SQL Developer', 'Senior Statistician', 'Senior Structural Engineer',
            'Senior Supply Chain Analyst', 'Senior Supply Chain Manager',
            'Senior Systems Administrator', 'Senior Systems Analyst',
            'Senior Systems Engineer', 'Senior Talent Acquisition Specialist',
            'Senior Tax Accountant', 'Senior Technical Writer',
            'Senior Training Specialist', 'Senior UX Designer', 'Senior Web Developer',
            'Senior Welder', 'SEO Manager', 'SEO Specialist', 'Server',
            'Service Desk Analyst', 'Sheet Metal Worker', 'Site Reliability Engineer',
            'Site Superintendent', 'Social Media Analyst', 'Social Media Coordinator',
            'Social Media Content Creator', 'Social Media Manager',
            'Social Media Specialist', 'Social Services Manager', 'Social Worker',
            'SOC Analyst', 'Solar Energy Specialist', 'Solar Installation Technician',
            'Sommelier', 'Sound Engineer', 'Sous Chef', 'Special Education Teacher',
            'Speechwriter', 'SQL Developer', 'Staff Accountant', 'Staff Data Scientist',
            'Staff Machine Learning Engineer', 'Staff Nurse', 'Staff Software Engineer',
            'Staffing Coordinator', 'Statistician', 'Store Manager',
            'Strategic Advisor', 'Structural Engineer', 'Substance Abuse Counselor',
            'Superintendent', 'Supply Chain Analyst', 'Supply Chain Manager',
            'Supply Planner', 'Surgeon', 'Surgical Technologist',
            'Sustainability Manager', 'Systems Analyst', 'Systems Engineer',
            'Systems Integrator', 'Talent Acquisition Manager',
            'Talent Acquisition Specialist', 'Talent Development Manager',
            'Talent Manager', 'Tax Accountant', 'Tax Consultant', 'Tax Director',
            'Tax Manager', 'Teacher', 'Teaching Assistant',
            'Technical Account Manager', 'Technical Product Manager',
            'Technical Project Manager', 'Technical Recruiter',
            'Technical Sales Representative', 'Technical Support Engineer',
            'Technical Support Specialist', 'Technical Writer',
            'Telemedicine Coordinator', 'Territory Sales Manager', 'Train Conductor',
            'Training Coordinator', 'Training Manager', 'Training Specialist',
            'Transaction Coordinator', 'Translator', 'Transportation Manager',
            'Transportation Planner', 'Transportation Safety Manager', 'Travel Agent',
            'Travel Coordinator', 'Travel Nurse', 'Treasurer', 'Truck Driver',
            'Tutor', 'UI Designer', 'UI/UX Designer', 'Ultrasound Technician',
            'Urban Planner', 'UX Designer', 'UX Researcher', 'Venture Partner',
            'Veterinarian', 'Veterinary Assistant', 'Veterinary Technician',
            'Vice President of Engineering', 'Vice President of Finance',
            'Vice President of HR', 'Vice President of IT',
            'Vice President of Marketing', 'Vice President of Operations',
            'Vice President of Product Management', 'Vice President of Sales',
            'Vice President of Software Engineering', 'Vice President of Supply Chain',
            'Video Editor', 'Videographer', 'Virtual Assistant',
            'Virtual Executive Assistant', 'Visual Designer', 'Visual Merchandiser',
            'Volunteer Coordinator', 'VP of Communications', 'VP of Creative',
            'VP of IT', 'VP of Product', 'Warehouse Associate', 'Warehouse Manager',
            'Warehouse Supervisor', 'Web Administrator', 'Web Designer', 'Web Developer',
            'Welder', 'Wind Turbine Technician', 'WordPress Developer',
            'Workforce Planning Analyst', 'Youth Mentor', 'Yoga Instructor',
            'Zoologist', 'Account Coordinator', 'Account Specialist',
            'Accounts Payable Clerk', 'Accounts Payable Manager',
            'Accounts Receivable Clerk', 'Accounts Receivable Manager',
            'Actuarial Analyst', 'Actuary', 'Administrative Trainee',
            'Admissions Representative', 'Aesthetic Nurse', 'Air Traffic Controller',
            'Analytical Chemist', 'Archivist', 'Assembly Line Worker',
            'Asset Manager', 'Associate Architect', 'Attending Physician',
            'Attending Surgeon', 'Audience Analyst', 'Back-End Developer',
            'Background Investigator', 'Benefits Coordinator', 'Billing Specialist',
            'Brand Strategist', 'Broker', 'Budget Manager', 'Business Process Analyst',
            'Category Manager', 'CDL Driver', 'Certified Financial Planner',
            'Chauffeur', 'Claims Examiner', 'Clinical Informatics Specialist',
            'Closing Coordinator', 'CNC Operator', 'Collections Manager',
            'Commodities Trader', 'Community Engagement Specialist',
            'Compliance Coordinator', 'Computer Technician', 'Content Marketing Manager',
            'Contracts Manager', 'Corporate Lawyer', 'Cost Estimator',
            'Curriculum Developer', 'Customs Broker', 'Data Entry Specialist',
            'Datacenter Technician', 'Dean of Students', 'Delivery Driver',
            'Dental Assistant', 'Department Head', 'Diplomatic Officer',
            'Director of Philanthropy', 'Distribution Manager', 'Dock Worker',
            'Document Control Specialist', 'Drafter', 'Driver', 'E-commerce Specialist',
            'Education Consultant', 'Electrologist', 'Elevator Technician',
            'Emergency Medical Technician', 'Employee Experience Manager',
            'Energy Auditor', 'Entry Level Financial Analyst',
            'Entry Level Software Engineer', 'Environmental Health Specialist',
            'Environmental Policy Analyst', 'Escalation Manager',
            'Executive Chairperson', 'Facility Coordinator', 'Family Therapist',
            'Fashion Show Stylist', 'Field Technician', 'File Clerk', 'Film Director',
            'Fire Captain', 'Fire Marshal', 'Firefighter', 'Fleet Coordinator',
            'Food Safety Inspector', 'Foreign Language Teacher', 'Freight Broker',
            'Front Desk Coordinator', 'Fundraising Officer', 'General Counsel',
            'Glazier', 'Government Affairs Manager', 'Groundskeeper',
            'Group Product Manager', 'HVAC Installer', 'Health Coach',
            'Hedge Fund Manager', 'Help Desk Supervisor', 'Home Health Nurse',
            'Hospital Administrator', 'HR Operations Director',
            'Human Resources Consultant', 'Illustrator', 'Immigration Attorney',
            'Industrial Hygienist', 'Information Clerk', 'Infrastructure Engineer',
            'Inside Sales Manager', 'Intelligence Officer', 'Interpreter',
            'Investment Banking Analyst', 'Investment Banking Associate',
            'IT Technician', 'Journeyman Electrician', 'Journeyman Plumber',
            'Key Account Sales Manager', 'Lead Architect', 'Lead Electrical Engineer',
            'Lead Instructor', 'Lead Teacher', 'Leasing Agent', 'Legal Coordinator',
            'Life Coach', 'Litigation Support Specialist', 'Loan Processor',
            'Loss Prevention Officer', 'Machine Learning Research Scientist',
            'Maintenance Director', 'Maintenance Engineer', 'Maintenance Manager',
            'Market Development Representative', 'Materials Coordinator',
            'Media Coordinator', 'Medical Administrator', 'Medical Laboratory Technician',
            'Meeting Coordinator', 'Mental Health Case Manager',
            'Merger and Acquisitions Analyst', 'Mobile Developer',
            'Mortgage Underwriter', 'Move Coordinator', 'Museum Curator',
            'Network Security Engineer', 'Notary Public', 'Nurse Educator',
            'Nurse Navigator', 'Nutritional Consultant', 'Occupational Health Specialist',
            'Office Support Specialist', 'Online ESL Instructor',
            'Order Support Specialist', 'Organizational Development Manager',
            'Outreach Coordinator', 'Patient Advocate', 'Performance Analyst',
            'Pharmacy Director', 'Physical Security Analyst', 'Pipeline Engineer',
            'Plant Operator', 'Policy Manager', 'Portfolio Analyst',
            'Practice Administrator', 'Practice Manager', 'Principal Data Scientist',
            'Process Analyst', 'Produce Manager', 'Product Compliance Specialist',
            'Program Evaluator', 'Property Accountant', 'Proposal Manager',
            'Provider Relations Specialist', 'Public Health Analyst',
            'Public Health Educator', 'Public Policy Analyst', 'Purchasing Coordinator',
            'Quality Improvement Nurse', 'Radiation Therapist',
            'Real Estate Investment Analyst', 'Regional Director',
            'Regulatory Compliance Manager', 'Reimbursement Specialist',
            'Remote Chat Agent', 'Research Director', 'Reservations Agent',
            'Retail Buyer', 'Retail District Manager', 'Revenue Cycle Manager',
            'Revenue Operations Manager', 'Risk Management Specialist',
            'Room Attendant', 'Safety Coordinator', 'Sales Development Manager',
            'Sales Executive', 'Sales Operations Analyst', 'Salon Manager',
            'Scheduling Coordinator', 'Security Operations Manager',
            'Senior Consultant', 'Senior Director of Engineering',
            'Senior Director of Finance', 'Senior Director of HR',
            'Senior Director of Marketing', 'Senior Director of Operations',
            'Senior Director of Sales', 'Senior Director of Technology',
            'Senior IT Analyst', 'Senior Legal Analyst', 'Senior Principal Engineer',
            'Senior Vice President of Finance', 'Senior Vice President of Marketing',
            'Senior Vice President of Operations', 'Senior Vice President of Sales',
            'Service Advisor', 'Shift Supervisor', 'Social Media Director',
            'Solutions Engineer', 'Sourcing Manager', 'Spa Coordinator',
            'Special Projects Manager', 'Sponsorship Manager', 'Staffing Manager',
            'Sterile Processing Technician', 'Strategic Partnerships Manager',
            'Student Advisor', 'Substitute Teacher', 'Supply Chain Director',
            'Survey Researcher', 'Systems Administrator', 'Tax Specialist',
            'Technical Analyst', 'Technical Consultant', 'Technical Director',
            'Technical Specialist', 'Telecommunications Engineer', 'Telemedicine Nurse',
            'Test Engineer', 'Trade Compliance Specialist', 'Trade Show Coordinator',
            'Transportation Analyst', 'Transportation Coordinator', 'Treasury Analyst',
            'Trust Officer', 'UI Developer', 'Ultrasound Technologist',
            'User Experience Researcher', 'Vendor Manager',
            'Veterans Services Coordinator', 'Vice Principal', 'Video Game Writer',
            'Virtual Recruiter', 'Volunteer Manager', 'Wealth Manager',
            'Wedding Coordinator', 'Wedding Stylist', 'Workforce Analyst',
            'Workforce Development Specialist', 'Workforce Planning Manager',
            'Workers Compensation Specialist', 'Zoning Administrator', 'Zoo Keeper',
        ];
    }
}
