<?php

namespace Database\Seeders;

use App\Models\JobListing;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

/**
 * 50 detailed Star Trek and Star Wars job listings for local testing.
 * Run by the local /reset route, or directly:
 *   php artisan db:seed --class=SciFiJobListingsSeeder
 */
class SciFiJobListingsSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->jobs() as $job) {
            $slug = Str::slug("{$job['company']}-{$job['title']}-{$job['location']}");

            JobListing::updateOrCreate(
                ['external_id' => 'scifi-'.Str::limit($slug, 180, '')],
                [
                    'title' => $job['title'],
                    'company' => $job['company'],
                    'location' => $job['location'],
                    'job_url' => "https://{$job['host']}/careers/{$slug}",
                    'description' => $this->describe($job),
                ],
            );
        }
    }

    /**
     * @param  array{summary: string, duties: array<int, string>, requirements: array<int, string>, pay: string, perks: string, type: string}  $job
     */
    private function describe(array $job): string
    {
        $bullets = fn (array $items): string => collect($items)->map(fn (string $item) => "• {$item}")->implode("\n");

        return implode("\n\n", [
            $job['summary'],
            "Responsibilities:\n".$bullets($job['duties']),
            "Requirements:\n".$bullets($job['requirements']),
            "Compensation: {$job['pay']}\nBenefits: {$job['perks']}\nEmployment type: {$job['type']}",
        ]);
    }

    /**
     * @return array<int, array{title: string, company: string, host: string, location: string, type: string, pay: string, summary: string, duties: array<int, string>, requirements: array<int, string>, perks: string}>
     */
    private function jobs(): array
    {
        return [...$this->starTrekJobs(), ...$this->starWarsJobs()];
    }

    /** @return array<int, array<string, mixed>> */
    private function starTrekJobs(): array
    {
        $starfleet = ['company' => 'Starfleet Command', 'host' => 'careers.starfleet.ufp.gov'];
        $federation = ['company' => 'United Federation of Planets', 'host' => 'jobs.ufp.gov'];

        return [
            [...$starfleet, 'title' => 'Chief Engineer', 'location' => 'USS Enterprise NCC-1701-D', 'type' => 'Full-time, five-year deep-space tour',
                'pay' => 'Federation post-scarcity allocation; unlimited replicator credit and holodeck priority',
                'summary' => 'The flagship of the Federation seeks a Chief Engineer to own the Galaxy-class warp core, main power distribution, and a 100-person engineering department. You will keep the ship at warp through ion storms, subspace anomalies, and the occasional Borg incursion — often with minutes to spare.',
                'duties' => ['Maintain matter/antimatter reaction assembly efficiency above 97% and brief the captain on any deviation', 'Lead damage-control teams during Red Alert and coordinate with the bridge on power rerouting', 'Supervise dilithium crystal inspection, recrystallization, and replacement schedules', 'Mentor junior engineers and run weekly Jefferies-tube safety drills'],
                'requirements' => ['Starfleet Academy engineering track with 10+ years shipboard service', 'Deep familiarity with Galaxy-class systems, EPS conduits, and saucer separation procedures', 'Proven ability to deliver "miracle" repairs under hard deadlines — and report honest time estimates'],
                'perks' => 'Private quarters on Deck 8, VISOR/prosthetic support, Ten Forward access, full family accommodation aboard'],
            [...$starfleet, 'title' => 'Ship\'s Counselor', 'location' => 'USS Enterprise NCC-1701-E', 'type' => 'Full-time, senior staff',
                'pay' => 'Senior officer allocation; Commander-grade quarters',
                'summary' => 'Serve on the bridge as the captain\'s advisor on first-contact psychology and crew morale. You will read hostile commanders across viewscreens, support crew through traumatic missions, and run the ship\'s mental-health program for 855 personnel.',
                'duties' => ['Advise the captain in real time during diplomatic and tactical encounters', 'Provide individual and group counseling for crew and civilian families', 'Assess officer fitness for duty after away-team incidents', 'Design morale programming with the Ten Forward and holodeck staff'],
                'requirements' => ['Advanced degree in psychology or xenopsychology from a Federation institution', 'Empathic or telepathic ability preferred but not required', 'Bridge-officer qualification (or willingness to pass the command exam)'],
                'perks' => 'Chocolate replicator allowance, flexible counseling schedule, Betazoid cultural leave'],
            [...$starfleet, 'title' => 'Chief Medical Officer', 'location' => 'USS Voyager NCC-74656 (Delta Quadrant)', 'type' => 'Full-time, indefinite deployment',
                'pay' => 'Standard Starfleet allocation; replicator rations are limited on this posting',
                'summary' => 'Voyager is 70,000 light-years from home and needs a CMO who can run sickbay with no resupply. You will treat unknown alien pathogens, manage the Emergency Medical Hologram, and make triage calls without Starfleet Medical backup.',
                'duties' => ['Run sickbay operations, surgery, and crew-wide physicals', 'Research and synthesize treatments for Delta Quadrant diseases', 'Collaborate with the EMH on subroutine updates and bedside manner', 'Maintain medical ethics standards in a starship far beyond Federation oversight'],
                'requirements' => ['Doctorate of medicine with xenobiology specialization', 'Comfort working alongside a photonic colleague with strong opinions', 'Ability to improvise with limited supplies and no chance of rotation home'],
                'perks' => 'Holodeck time (power permitting), Neelix\'s cooking, and a crew that becomes family'],
            [...$starfleet, 'title' => 'Tactical Officer', 'location' => 'USS Defiant NX-74205', 'type' => 'Full-time, frontline wartime posting',
                'pay' => 'Wartime hazard allocation plus Dominion War service commendation eligibility',
                'summary' => 'The Defiant is overgunned, overpowered, and on the front line of the Dominion War. We need a Tactical Officer to run quantum torpedoes, pulse phasers, and the cloaking device on loan from the Romulan Star Empire.',
                'duties' => ['Operate weapons and shields during fleet engagements with Jem\'Hadar attack ships', 'Maintain cloaking device compliance with the Treaty of Algeron exemption', 'Lead security for away missions and boarding actions', 'Run daily weapons diagnostics and combat simulations'],
                'requirements' => ['Tactical specialization with combat command experience', 'Ability to operate in cramped quarters with no Ten Forward', 'Security clearance for Romulan technology'],
                'perks' => 'Deep Space Nine promenade access, Quark\'s bar tab (at your own risk), holosuite discounts'],
            [...$starfleet, 'title' => 'Science Officer', 'location' => 'USS Discovery NCC-1031 (32nd century)', 'type' => 'Full-time, temporal relocation required',
                'pay' => 'Federation allocation; programmable-matter uniform included',
                'summary' => 'Join a crew that jumped 930 years into the future. As Science Officer you will analyze the Burn, support spore-drive navigation, and help rebuild a fractured Federation one reconnected world at a time.',
                'duties' => ['Lead scientific analysis of subspace anomalies and dark-matter phenomena', 'Support the spore-drive navigator and mycelial network research', 'Catalogue 32nd-century technology for crew retraining', 'Brief the captain on first-contact science implications'],
                'requirements' => ['Doctorate in astrophysics, xenobiology, or subspace theory', 'Emotional resilience — you will not see your original century again', 'Comfort with detached nacelles and personal transporters'],
                'perks' => 'Personal transporter badge, cats welcome, direct access to Federation HQ'],
            [...$starfleet, 'title' => 'Helm Officer', 'location' => 'USS Cerritos NCC-75567', 'type' => 'Full-time, second-contact specialist',
                'pay' => 'Standard allocation; lower-decks bunk to start with promotion path',
                'summary' => 'The Cerritos handles second contact — the unglamorous follow-up after the flagship leaves. We need a pilot who can dodge space debris, land shuttles in hostile weather, and stay calm while the rest of the ship is on fire.',
                'duties' => ['Pilot the California-class starship during standard and emergency maneuvers', 'Fly shuttle runs for away teams and supply missions', 'Coordinate with operations on sensor-guided navigation', 'Train ensigns on evasive flight patterns'],
                'requirements' => ['Starfleet Academy flight certification', 'Excellent reflexes and tolerance for absurd mission briefs', 'Team player willing to share quarters in the hallway'],
                'perks' => 'Promotion fast-track for high performers, holodeck adventure credits, captain\'s open door'],
            [...$starfleet, 'title' => 'Starbase Operations Chief', 'location' => 'Deep Space Nine, Bajoran Wormhole', 'type' => 'Full-time, station posting',
                'pay' => 'Operations allocation plus Bajoran provisional government stipend',
                'summary' => 'Keep a Cardassian-built mining station running as the gateway to the Gamma Quadrant. You will fight rewiring written by people who never documented anything, manage docking traffic, and keep the replicators from serving Cardassian fish juice.',
                'duties' => ['Maintain station power, life support, and docking pylons', 'Reverse-engineer Cardassian systems and replace them with Federation standards', 'Schedule wormhole transit traffic with Bajoran control', 'Supervise engineering crews during Dominion-era alert conditions'],
                'requirements' => ['Non-commissioned or commissioned engineering background', 'Patience with Cardassian design philosophy', 'Experience with both starship and station infrastructure'],
                'perks' => 'Family quarters on the habitat ring, Ops-level clearance, darts at Quark\'s'],
            [...$starfleet, 'title' => 'Academy Flight Instructor', 'location' => 'Starfleet Academy, San Francisco, Earth', 'type' => 'Full-time, academic appointment',
                'pay' => 'Instructor allocation plus housing in the Presidio',
                'summary' => 'Train the next generation of starship pilots. You will teach flight theory, supervise shuttle trials over Saturn\'s rings, and enforce the lessons we learned from Nova Squadron.',
                'duties' => ['Teach flight mechanics, warp theory, and emergency procedures', 'Oversee live flight exercises and simulator certification', 'Evaluate cadets for Red Squad and advanced tracks', 'Enforce Academy honor code on flight safety'],
                'requirements' => ['Minimum 8 years of starship piloting experience', 'Clean flight-safety record', 'Teaching or mentorship experience'],
                'perks' => 'Campus gardens, Boothby-maintained grounds, sabbatical rotation to deep space'],
            [...$starfleet, 'title' => 'Transporter Chief', 'location' => 'USS Titan NCC-80102', 'type' => 'Full-time, senior NCO',
                'pay' => 'Chief petty officer allocation',
                'summary' => 'Beam people safely from point A to point B with every molecule in the right order. You will run transporter rooms, handle pattern buffer emergencies, and guard against the rare-but-memorable duplication incident.',
                'duties' => ['Operate and maintain primary and cargo transporter systems', 'Lock onto away teams through interference and emergency extraction scenarios', 'Run pattern-buffer diagnostics and Heisenberg compensator calibration', 'Log all transport activity for security review'],
                'requirements' => ['Transporter operations certification level 4 or higher', 'Steady hands and a calm voice during ionic storms', 'Familiarity with Federation transporter safety regulations'],
                'perks' => 'Titan\'s diverse crew, excellent mess hall, generous shore leave'],
            [...$starfleet, 'title' => 'Borg Liberation Counselor', 'location' => 'Fenris Ranger Outpost, Beta Quadrant', 'type' => 'Contract, 2-year renewable',
                'pay' => 'Federation grant funding plus hazard stipend',
                'summary' => 'Help former drones reclaim their individuality. You will support ex-Borg through implant removal recovery, identity rediscovery, and resettlement on worlds that may not want them.',
                'duties' => ['Deliver trauma-informed counseling to liberated drones', 'Coordinate with medical staff on cybernetic removal plans', 'Advocate for resettlement rights with planetary governments', 'Maintain confidential case records under Federation privacy law'],
                'requirements' => ['Counseling or social-work credential', 'Knowledge of Borg collective neurology', 'Willingness to work in lawless border regions'],
                'perks' => 'Meaningful work, flexible leave, Starfleet medical coverage'],
            [...$starfleet, 'title' => 'Temporal Investigations Agent', 'location' => 'Department of Temporal Investigations, Earth', 'type' => 'Full-time, classified',
                'pay' => 'Federation civil-service grade 14',
                'summary' => 'Starship captains keep breaking the timeline, and someone has to file the paperwork. You will investigate unauthorized time travel incidents, interview officers with suspiciously good memories, and enforce the Temporal Prime Directive.',
                'duties' => ['Investigate reported temporal incursions and predestination paradoxes', 'Debrief crews returning from time travel incidents', 'Maintain the classified temporal incident archive', 'Coordinate with the 29th-century Temporal Integrity Commission when they bother to show up'],
                'requirements' => ['Background in physics, law, or intelligence', 'No sense of humor about the word "temporal"', 'Top-secret clearance'],
                'perks' => 'Stable 9-to-5 hours (in the current timeline), pension indexed to any timeline'],
            [...$starfleet, 'title' => 'Holodeck Program Designer', 'location' => 'Utopia Planitia Fleet Yards, Mars', 'type' => 'Full-time, hybrid (on-site and remote subspace)',
                'pay' => 'Engineering specialist allocation plus royalties on crew-favorite programs',
                'summary' => 'Build the holonovels, training simulations, and recreation programs that keep crews sane on long missions. You will also own holodeck safety — and make absolutely sure the safety protocols cannot be switched off by a stray voice command.',
                'duties' => ['Design and script holoprograms for training and recreation', 'Implement and audit safety-protocol interlocks', 'Prevent holographic characters from achieving unplanned sentience (or escalate when they do)', 'Test programs with crew focus groups before fleet release'],
                'requirements' => ['Background in holographic engineering or interactive narrative design', 'Strong grasp of photonic physics and replicator-matter integration', 'Portfolio of shipped holoprograms'],
                'perks' => 'Unlimited holodeck test time, creative credit in the Starfleet program library, Mars colony housing'],
            [...$federation, 'title' => 'Diplomatic Attaché', 'location' => 'Federation Embassy, Qo\'noS', 'type' => 'Full-time, diplomatic posting',
                'pay' => 'Diplomatic corps grade 12 plus hardship allowance',
                'summary' => 'Represent the Federation at the heart of the Klingon Empire. You will attend High Council sessions, navigate House politics, and occasionally stand as a witness at a ritual challenge.',
                'duties' => ['Draft and deliver diplomatic communiqués to the Chancellor\'s office', 'Monitor Great House alliances and report shifts to the Federation Council', 'Negotiate trade and border agreements under the Khitomer Accords', 'Host cultural exchange events (bloodwine will be served)'],
                'requirements' => ['Fluency in tlhIngan Hol', 'Diplomatic corps certification', 'High pain tolerance and a strong stomach for gagh'],
                'perks' => 'Embassy housing, security detail, honor-bound hosts'],
            [...$federation, 'title' => 'Terraforming Project Manager', 'location' => 'Genesis Planet Resettlement Office, Mutara Sector', 'type' => 'Full-time, project-based',
                'pay' => 'Federation science grant, grade 13',
                'summary' => 'Lead a multi-year terraforming initiative using post-Genesis-era, rigorously tested methods. You will coordinate geologists, climate engineers, and colonists to turn a barren world into a home — safely this time.',
                'duties' => ['Plan and track terraforming phases across atmosphere, hydrosphere, and biosphere', 'Manage a 60-person interdisciplinary team', 'Report progress and risk to the Federation Science Council', 'Enforce strict protomatter-free protocols'],
                'requirements' => ['Degree in planetary science or environmental engineering', '5+ years managing large scientific projects', 'Strong ethics around life-creation technology'],
                'perks' => 'Naming rights to one mountain range, colonist housing, research publication support'],
            [...$federation, 'title' => 'Colony Administrator', 'location' => 'Tau Ceti Prime', 'type' => 'Full-time, elected-appointed hybrid',
                'pay' => 'Colony stipend plus Federation administrative allowance',
                'summary' => 'Run day-to-day administration of a growing Federation colony of 40,000 residents. You will manage infrastructure, disputes, and relations with Starfleet when it inevitably parks a starship in orbit.',
                'duties' => ['Oversee colony infrastructure, agriculture, and public services', 'Mediate disputes between colonists and settlement councils', 'Coordinate emergency response with Starfleet during crises', 'Prepare the annual report to the Federation Council'],
                'requirements' => ['Public-administration or civil-engineering background', 'Consensus-building skills', 'Residency on Tau Ceti Prime within 90 days'],
                'perks' => 'Colony residence, transport subsidy to Earth, community festivals'],
            ['company' => 'Ferengi Commerce Authority', 'host' => 'fca.ferenginar.fer', 'title' => 'Latinum Accounts Analyst', 'location' => 'Ferenginar', 'type' => 'Full-time, commission-heavy',
                'pay' => '12 bars of gold-pressed latinum per quarter plus 3% of recovered profit',
                'summary' => 'The FCA audits every business in the Alliance. We need an analyst who can smell hidden profit across three quadrants and apply the Rules of Acquisition with ruthless consistency.',
                'duties' => ['Audit merchant ledgers for unreported profit', 'Model latinum exchange rates across Gamma and Alpha Quadrant markets', 'Prepare cases for FCA liquidators', 'Recommend penalties in accordance with the Ferengi Bill of Opportunities'],
                'requirements' => ['Recite the Rules of Acquisition from memory', 'Advanced degree in commerce or equivalent street experience', 'Never give anything away for free (Rule 18 applies to your résumé too)'],
                'perks' => 'Oo-mox allowance, discounted tube grubs, Grand Nagus annual audience'],
            ['company' => 'Quark\'s Bar, Grill, Gaming House and Holosuite Arcade', 'host' => 'quarks.ds9.bajor', 'title' => 'Dabo Table Manager', 'location' => 'Deep Space Nine Promenade', 'type' => 'Full-time, evenings',
                'pay' => '0.4 strips of latinum per shift plus tips (house takes 30%)',
                'summary' => 'Run the busiest Dabo tables on the Promenade. You will manage dealers, spot cheaters, and keep the house edge exactly where Quark wants it — while keeping Odo satisfied that everything is legal.',
                'duties' => ['Supervise Dabo dealers and rotation schedules', 'Monitor wheel integrity and flag suspected tampering', 'Resolve customer disputes with charm and firmness', 'Report nightly take to management'],
                'requirements' => ['Casino or hospitality management experience', 'Charisma; ability to shout "Dabo!" with conviction', 'Clean record with station security'],
                'perks' => 'Free synthehol, holosuite discount, staff lounge (union-negotiated)'],
            ['company' => 'Daystrom Institute', 'host' => 'careers.daystrom.edu', 'title' => 'Artificial Life Researcher', 'location' => 'Daystrom Institute, Okinawa, Earth', 'type' => 'Full-time, research tenure-track',
                'pay' => 'Research fellowship allocation plus lab budget of 2M Federation credits',
                'summary' => 'Advance the study of synthetic life in the tradition of Dr. Noonien Soong — with far more ethics oversight. You will research positronic neural networks and help shape Federation policy on synthetic rights.',
                'duties' => ['Conduct research on positronic brain architecture and emergent consciousness', 'Publish findings in peer-reviewed Federation journals', 'Advise the Federation Council on synthetic-rights legislation', 'Supervise graduate researchers and lab safety'],
                'requirements' => ['Doctorate in cybernetics, AI, or neuroscience', 'Published work in synthetic cognition', 'Commitment to the Data precedent: artificial beings are persons'],
                'perks' => 'Sabbatical program, Daystrom Station access, collaboration with the Sona and Coppelius communities'],
            ['company' => 'Klingon Defense Force', 'host' => 'kdf.qonos.kli', 'title' => 'Bird-of-Prey Weapons Officer', 'location' => 'IKS Rotarran', 'type' => 'Full-time, combat duty',
                'pay' => 'Warrior\'s share of plunder plus House stipend',
                'summary' => 'Glory awaits. The IKS Rotarran seeks a Weapons Officer to fire disruptors, time the cloak, and bring honor to the ship in battle. Today is a good day to apply.',
                'duties' => ['Operate disruptor cannons and photon torpedo launchers', 'Coordinate decloak-and-strike timing with the helm', 'Maintain weapons readiness during long patrols', 'Uphold warrior discipline among the gunnery crew'],
                'requirements' => ['Honorable combat record', 'Fluency in tlhIngan Hol', 'Proficiency with bat\'leth for close-quarters disputes'],
                'perks' => 'Bloodwine rations, Sto-vo-kor eligibility, song written in your honor upon glorious death'],
            ['company' => 'Vulcan Science Academy', 'host' => 'vsa.shikahr.vul', 'title' => 'Research Logician', 'location' => 'ShiKahr, Vulcan', 'type' => 'Full-time, permanent',
                'pay' => 'Academy stipend — compensation is logical, not generous',
                'summary' => 'The Vulcan Science Academy seeks a Research Logician to contribute to theoretical physics and applied logic. Emotional outbursts will be noted and gently corrected.',
                'duties' => ['Conduct research in subspace mechanics and probability theory', 'Review peer submissions with rigorous logical analysis', 'Teach meditative discipline alongside scientific method', 'Contribute to Academy archives at Mount Seleya'],
                'requirements' => ['Mastery of Kolinahr disciplines preferred', 'Doctorate in physics, mathematics, or philosophy of logic', 'Tolerance for 60°C ambient temperatures'],
                'perks' => 'Quiet workspace, meditation retreats, excellent plomeek soup'],
            ['company' => 'Romulan Star Empire', 'host' => 'careers.romulus.rse', 'title' => 'Tal Shiar Intelligence Analyst', 'location' => 'Romulus', 'type' => 'Full-time, undisclosed',
                'pay' => 'Classified. Loyalty is rewarded; disloyalty is also addressed.',
                'summary' => 'The Tal Shiar seeks an analyst to assess Federation and Klingon strategic movements. You will synthesize intercepted communications and advise the Praetor. This posting does not exist.',
                'duties' => ['Analyze intercepted subspace traffic along the Neutral Zone', 'Maintain profiles on Federation starship captains', 'Identify dissident activity within the Senate', 'Brief superiors with absolute discretion'],
                'requirements' => ['Unquestioned loyalty to the Empire', 'Fluency in Federation Standard and Klingon', 'Ability to keep secrets from your own family'],
                'perks' => 'Senate district housing, Romulan ale (legal here), personal cloaking clearance'],
            ['company' => 'Cardassian Central Command', 'host' => 'cc.cardassia.cu', 'title' => 'Orbital Station Architect', 'location' => 'Cardassia Prime', 'type' => 'Full-time, state service',
                'pay' => 'State architect\'s grade plus family honor bonus',
                'summary' => 'Design the next generation of Cardassian orbital stations. Your work will combine aesthetic authority, structural efficiency, and just enough deliberately confusing layout to keep occupants disoriented.',
                'duties' => ['Design station superstructures and docking arrays', 'Integrate ore-processing and defensive platforms', 'Coordinate with Obsidian Order on security features', 'Present designs to Central Command review boards'],
                'requirements' => ['Degree in orbital architecture', 'Portfolio of completed space structures', 'Loyalty to the State above all'],
                'perks' => 'Heated quarters, state honors, a copy of The Never Ending Sacrifice'],
            ['company' => 'Bajoran Provisional Government', 'host' => 'jobs.bajor.gov', 'title' => 'Agricultural Restoration Specialist', 'location' => 'Dahkur Province, Bajor', 'type' => 'Full-time, public service',
                'pay' => 'Provisional government salary plus land-grant option',
                'summary' => 'Help Bajor recover from the Occupation. You will restore soil poisoned by Cardassian strip-mining and bring farming communities back to self-sufficiency.',
                'duties' => ['Survey and remediate contaminated farmland', 'Deploy soil reclamators and irrigation systems', 'Train farming collectives in modern techniques', 'Report progress to the Chamber of Ministers'],
                'requirements' => ['Agronomy or environmental engineering background', 'Experience with post-conflict recovery', 'Respect for Bajoran spiritual traditions'],
                'perks' => 'Land-grant eligibility, festival leave, Vedek blessings'],
            ['company' => 'Section 31', 'host' => 'section31.invalid', 'title' => 'Operations Specialist', 'location' => 'Location withheld', 'type' => 'Full-time, deniable',
                'pay' => 'Competitive. You will not be able to discuss it.',
                'summary' => 'An organization that does not officially exist is seeking an Operations Specialist to protect the Federation from threats others are unwilling to confront. We will contact you. We already know how.',
                'duties' => ['Execute covert operations beyond the reach of Starfleet oversight', 'Gather intelligence on existential threats to the Federation', 'Maintain cover identities across multiple postings', 'Report only to your handler'],
                'requirements' => ['Exceptional operational skills', 'Moral flexibility', 'Willingness to never be acknowledged'],
                'perks' => 'Black badge, unlimited travel, your file will be erased'],
            ['company' => 'Starfleet Corps of Engineers', 'host' => 'sce.starfleet.ufp.gov', 'title' => 'Warp Field Specialist', 'location' => 'USS da Vinci NCC-81623', 'type' => 'Full-time, mobile team',
                'pay' => 'Engineering specialist allocation plus field-deployment bonus',
                'summary' => 'The S.C.E. fixes what nobody else can. As a Warp Field Specialist you will travel to disabled starships, ancient alien installations, and failing colonies to restore propulsion and power.',
                'duties' => ['Diagnose and repair warp field geometry faults', 'Reverse-engineer alien propulsion technologies', 'Deploy with rapid-response teams on 24-hour notice', 'Document repairs for the Starfleet engineering database'],
                'requirements' => ['Advanced warp theory qualification', 'Experience with non-Federation technology', 'Adaptability and a toolkit you trust'],
                'perks' => 'Constant variety, Corps camaraderie, first look at new technology'],
        ];
    }

    /** @return array<int, array<string, mixed>> */
    private function starWarsJobs(): array
    {
        $rebellion = ['company' => 'Alliance to Restore the Republic', 'host' => 'recruit.rebelalliance.org'];
        $newRepublic = ['company' => 'New Republic', 'host' => 'careers.newrepublic.gov'];

        return [
            [...$rebellion, 'title' => 'X-wing Pilot', 'location' => 'Echo Base, Hoth', 'type' => 'Full-time, combat',
                'pay' => '1,200 credits/month plus hazard pay; payment may be delayed by Imperial blockades',
                'summary' => 'Rogue Squadron is recruiting. Fly the T-65 X-wing against overwhelming Imperial odds, escort transports through blockades, and defend the base when walkers come over the ridge.',
                'duties' => ['Fly combat sorties and escort missions', 'Maintain your fighter alongside your astromech droid', 'Participate in daily flight drills and target practice', 'Scramble within 3 minutes of a base alert'],
                'requirements' => ['Proven piloting skill — bullseyeing womp rats counts', 'Cold-weather tolerance', 'Commitment to the Rebellion\'s cause'],
                'perks' => 'Assigned astromech, tauntaun transport, the undying gratitude of the galaxy'],
            [...$rebellion, 'title' => 'Intelligence Operative', 'location' => 'Yavin 4', 'type' => 'Full-time, field',
                'pay' => '1,500 credits/month plus mission expense account',
                'summary' => 'Rebel Intelligence needs operatives to infiltrate Imperial facilities, recruit informants, and retrieve plans the Empire would kill to protect. Many Bothans died to bring us the last batch.',
                'duties' => ['Conduct undercover operations in Imperial-held systems', 'Recruit and manage informant networks', 'Extract classified data and deliver it to Alliance High Command', 'Write concise mission reports for General Draven'],
                'requirements' => ['Tradecraft and surveillance experience', 'Ability to maintain cover under interrogation', 'Fluency in Basic plus two regional languages'],
                'perks' => 'Blaster of choice, false identity docs, jungle-temple accommodation'],
            [...$rebellion, 'title' => 'Field Medic', 'location' => 'Mobile Fleet, Outer Rim', 'type' => 'Full-time, deployed',
                'pay' => '1,300 credits/month plus bacta-stock bonus',
                'summary' => 'Keep Rebel soldiers alive. You will triage wounds on the battlefield, operate bacta tanks aboard medical frigates, and work alongside 2-1B surgical droids.',
                'duties' => ['Provide emergency medical care during ground operations', 'Manage bacta tank rotations and inventory', 'Train troops in basic combat first aid', 'Coordinate evacuations with transport crews'],
                'requirements' => ['Medical training (sentient species, multiple anatomies)', 'Composure under blaster fire', 'Experience with medical droids'],
                'perks' => 'Priority bacta access, frigate quarters, respect of every trooper you save'],
            [...$rebellion, 'title' => 'Ground Crew Mechanic', 'location' => 'Rebel Base, Dantooine', 'type' => 'Full-time',
                'pay' => '900 credits/month plus spare-parts salvage share',
                'summary' => 'Keep the fleet flying with whatever parts we can scrounge. You will repair starfighters between sorties, rebuild hyperdrives, and improvise when the supply run doesn\'t come.',
                'duties' => ['Repair and refuel X-wings, Y-wings, and A-wings', 'Diagnose hyperdrive and deflector shield faults', 'Salvage parts from damaged craft', 'Maintain hangar safety protocols'],
                'requirements' => ['Starship mechanics certification or equivalent experience', 'Creativity with limited parts', 'Ability to work around loud astromechs'],
                'perks' => 'Hangar mess hall, flight-training eligibility, tools you get to keep'],
            [...$newRepublic, 'title' => 'Senate Policy Advisor', 'location' => 'Chandrila', 'type' => 'Full-time',
                'pay' => '3,800 credits/month plus housing stipend',
                'summary' => 'Help build a democracy from the ashes of the Empire. You will draft legislation, research disarmament policy, and advise senators on the Military Disarmament Act.',
                'duties' => ['Draft and analyze legislation for the Galactic Senate', 'Brief senators on member-world concerns', 'Coordinate with committees on trade and security', 'Track Imperial Remnant activity for policy implications'],
                'requirements' => ['Background in political science or galactic law', 'Strong writing skills', 'Commitment to democratic governance'],
                'perks' => 'Chandrilan lakeside housing, Senate cafeteria, diplomatic travel'],
            [...$newRepublic, 'title' => 'New Republic Marshal', 'location' => 'Adelphi Base, Outer Rim', 'type' => 'Full-time, field enforcement',
                'pay' => '2,400 credits/month plus bounty-recovery bonuses',
                'summary' => 'Bring law to the Outer Rim. As a Marshal you will track Imperial war criminals, investigate crimes in lawless systems, and protect settlements the Senate forgets exist.',
                'duties' => ['Pursue fugitives and Imperial holdouts', 'Investigate crimes in Outer Rim settlements', 'Coordinate with local authorities and informal allies', 'File reports with the New Republic Security Bureau'],
                'requirements' => ['Law-enforcement or military experience', 'Proficiency with blaster and speeder', 'Sound judgment operating alone'],
                'perks' => 'Assigned X-wing, marshal badge, New Republic veteran benefits'],
            [...$newRepublic, 'title' => 'Amnesty Program Case Officer', 'location' => 'Coruscant', 'type' => 'Full-time',
                'pay' => '3,200 credits/month',
                'summary' => 'Help former Imperials transition into civilian life. You will evaluate candidates, manage placements, and assess whether rehabilitation is genuine.',
                'duties' => ['Interview amnesty candidates and assess risk', 'Match former Imperials to civilian job placements', 'Monitor progress and flag concerns', 'Liaise with the Bureau of Intelligence'],
                'requirements' => ['Social-work or corrections background', 'Strong interview and assessment skills', 'Discretion with sensitive files'],
                'perks' => 'Coruscant housing allowance, counseling support, mid-level clearance'],
            ['company' => 'Galactic Empire', 'host' => 'jobs.imperialcenter.emp', 'title' => 'Death Star Reactor Engineer', 'location' => 'DS-2 Death Star II, Endor orbit', 'type' => 'Full-time, construction deadline',
                'pay' => '4,000 Imperial credits/month; the Emperor is displeased by your apparent lack of progress',
                'summary' => 'Complete the main reactor of the second Death Star on an accelerated schedule. Lord Vader will personally review your timeline. Please ensure all exhaust ports are covered this time.',
                'duties' => ['Oversee hypermatter reactor construction and testing', 'Coordinate 200+ engineers and construction droids', 'Report progress to Moff Jerjerrod daily', 'Conduct thermal exhaust design reviews (critical)'],
                'requirements' => ['Degree in reactor engineering', 'Experience with planet-scale power systems', 'Ability to work under extreme managerial pressure'],
                'perks' => 'Imperial pension (conditions apply), officer\'s mess, a very large office'],
            ['company' => 'Galactic Empire', 'host' => 'jobs.imperialcenter.emp', 'title' => 'Stormtrooper Marksmanship Instructor', 'location' => 'Carida Academy', 'type' => 'Full-time, training',
                'pay' => '2,100 Imperial credits/month plus results bonus',
                'summary' => 'Improve stormtrooper accuracy across the Imperial Army. Every metric shows we need you more than ever. Results will be measured against a very low baseline.',
                'duties' => ['Design and run blaster training programs', 'Evaluate recruits on range and field exercises', 'Diagnose helmet-visibility issues with the armor division', 'Report quarterly accuracy improvements'],
                'requirements' => ['Military instructor experience', 'Expert marksmanship', 'Patience'],
                'perks' => 'Complimentary armor fitting, barracks housing, range access'],
            ['company' => 'Hutt Cartel', 'host' => 'jabbaspalace.tat', 'title' => 'Palace Majordomo', 'location' => 'Jabba\'s Palace, Tatooine', 'type' => 'Full-time, live-in',
                'pay' => '5,000 Wupiupi/month plus gifts from favored guests',
                'summary' => 'Manage the household of the galaxy\'s most notorious crime lord. You will greet guests, handle scheduling, and keep the rancor fed. Advancement opportunities depend on staying out of the rancor pit.',
                'duties' => ['Screen visitors and manage audience schedules', 'Oversee palace staff, droids, and entertainers', 'Negotiate minor contracts on behalf of His Excellency', 'Maintain the palace\'s trapdoor mechanisms'],
                'requirements' => ['Fluency in Huttese', 'Diplomacy under pressure', 'Excellent survival instincts'],
                'perks' => 'Palace quarters, desert views, band on retainer'],
            ['company' => 'Bounty Hunters\' Guild', 'host' => 'guild.nevarro.orr', 'title' => 'Bounty Hunter', 'location' => 'Nevarro', 'type' => 'Contract, per bounty',
                'pay' => 'Per-puck payment in Calamari flan or Imperial credits (market rates vary)',
                'summary' => 'The Guild offers steady work for skilled hunters. Collect tracking fobs, bring in quarries (warm preferred), and follow the Guild code. This is the way.',
                'duties' => ['Accept and complete bounty contracts', 'Track targets across the Outer Rim', 'Deliver quarries per contract terms', 'Maintain equipment and ship in operational condition'],
                'requirements' => ['Proficiency with tracking and combat', 'Own ship and weapons', 'Adherence to Guild code'],
                'perks' => 'Flexible schedule, beskar bonus for elite contracts, Guild bar tab'],
            ['company' => 'Mos Eisley Cantina', 'host' => 'cantina.moseisley.tat', 'title' => 'Bartender', 'location' => 'Mos Eisley, Tatooine', 'type' => 'Full-time, nights',
                'pay' => '600 credits/month plus tips',
                'summary' => 'Serve drinks at the galaxy\'s most wretched hive of scum and villainy. You will mix blue milk cocktails, break up fights, and enforce the no-droids policy.',
                'duties' => ['Prepare drinks for 40+ species with varied biochemistry', 'Manage bar inventory and supplier relationships', 'De-escalate conflicts before blasters come out', 'Enforce house rules at the door'],
                'requirements' => ['Bartending experience', 'Multilingual (Basic, Huttese, Rodian helpful)', 'Calm demeanor around wanted criminals'],
                'perks' => 'Free meals, live Bith band, very interesting clientele'],
            ['company' => 'Jedi Order', 'host' => 'temple.coruscant.jedi', 'title' => 'Jedi Archivist', 'location' => 'Jedi Temple Archives, Coruscant', 'type' => 'Full-time, lifetime service',
                'pay' => 'Jedi do not accept compensation; room and board provided',
                'summary' => 'Preserve the collected knowledge of the galaxy. You will curate holocrons, maintain star charts, and assist researchers. If an item is not in the archives, it does not exist — but please double-check anyway.',
                'duties' => ['Curate and protect holocrons and ancient texts', 'Maintain galactic star-chart records', 'Assist Jedi and scholars with research', 'Audit archives for tampering or missing entries'],
                'requirements' => ['Force sensitivity', 'Meticulous attention to detail', 'Humility about the limits of the archive'],
                'perks' => 'Temple residence, lightsaber training, galaxy\'s greatest library'],
            ['company' => 'Mandalorian Covert', 'host' => 'covert.mandalore.mdl', 'title' => 'Armorer\'s Apprentice', 'location' => 'Hidden Covert, Mandalore', 'type' => 'Full-time, apprenticeship',
                'pay' => 'Apprentice stipend plus beskar allotment',
                'summary' => 'Learn the sacred art of forging beskar. You will assist the Armorer in crafting armor, maintaining the forge, and preserving Mandalorian tradition.',
                'duties' => ['Assist in smelting and forging beskar', 'Maintain forge equipment and tools', 'Learn signet design and clan heraldry', 'Uphold the Creed at all times'],
                'requirements' => ['Commitment to the Way of the Mandalore', 'Metalworking aptitude', 'Never remove your helmet in front of others'],
                'perks' => 'Personal armor set, covert community, lifelong trade'],
            ['company' => 'Kuat Drive Yards', 'host' => 'careers.kuatdriveyards.com', 'title' => 'Star Destroyer Hull Engineer', 'location' => 'Kuat Orbital Shipyards', 'type' => 'Full-time',
                'pay' => '5,500 credits/month plus completion bonuses',
                'summary' => 'Design and inspect hull structures for the galaxy\'s largest warships. KDY builds the most feared capital ships in history, and our hull team makes sure they stay in one piece.',
                'duties' => ['Design hull plating and structural frameworks', 'Run stress simulations on capital-ship designs', 'Inspect welds and armor layers during construction', 'Collaborate with shield and weapons integration teams'],
                'requirements' => ['Degree in starship structural engineering', '5+ years in capital-ship construction', 'Experience with durasteel and quadanium alloys'],
                'perks' => 'Orbital housing, family-leave program, shipyard shuttle service'],
            ['company' => 'Incom Corporation', 'host' => 'jobs.incom.fresia', 'title' => 'Starfighter Test Pilot', 'location' => 'Fresia', 'type' => 'Full-time',
                'pay' => '4,800 credits/month plus hazard pay per test flight',
                'summary' => 'Fly next-generation starfighter prototypes before anyone else. You will push experimental craft to their limits and deliver honest feedback that shapes the next T-series design.',
                'duties' => ['Conduct flight tests on prototype starfighters', 'Record telemetry and report performance issues', 'Collaborate with engineers on design iterations', 'Maintain peak physical and piloting condition'],
                'requirements' => ['Military or civilian combat-pilot background', 'Record of safe high-risk flying', 'Technical communication skills'],
                'perks' => 'First access to new fighters, full medical, pilot lounge'],
            ['company' => 'Cloud City Mining Guild', 'host' => 'careers.cloudcity.bespin', 'title' => 'Tibanna Gas Operations Supervisor', 'location' => 'Cloud City, Bespin', 'type' => 'Full-time',
                'pay' => '3,500 credits/month plus production bonus',
                'summary' => 'Oversee Tibanna gas extraction in one of the most beautiful mining facilities in the galaxy. We are a small operation that doesn\'t fall under Imperial jurisdiction — for now.',
                'duties' => ['Supervise gas-processing and refinement operations', 'Manage Ugnaught work teams', 'Monitor safety systems and carbon-freezing chamber usage', 'Report production numbers to the Baron Administrator'],
                'requirements' => ['Industrial operations experience', 'Comfort with high altitudes', 'Diplomacy with unexpected Imperial visitors'],
                'perks' => 'Cloud City residence, sunset views, casino access'],
            ['company' => 'Chalmun\'s Spaceport Logistics', 'host' => 'docking.moseisley.tat', 'title' => 'Docking Bay Coordinator', 'location' => 'Docking Bay 94, Mos Eisley', 'type' => 'Full-time',
                'pay' => '750 credits/month plus docking-fee commission',
                'summary' => 'Coordinate arrivals and departures at a busy spaceport. You will schedule bays, collect fees, and politely decline to answer questions from Imperial patrols.',
                'duties' => ['Schedule docking bay usage and departures', 'Collect fees and maintain transaction logs', 'Inspect ships for basic safety compliance', 'Communicate with port authority and local enforcement'],
                'requirements' => ['Logistics or scheduling experience', 'Ability to tell a fast ship from a fast talker', 'Discretion'],
                'perks' => 'Discounted fuel, desert housing, stories to tell'],
            ['company' => 'Resistance', 'host' => 'join.resistance.dqr', 'title' => 'Command Communications Officer', 'location' => 'D\'Qar Base', 'type' => 'Full-time, wartime',
                'pay' => '1,400 credits/month; General Organa promises nothing but hope',
                'summary' => 'Keep the Resistance connected. You will manage encrypted communications, coordinate fleet operations, and relay orders under fire from the First Order.',
                'duties' => ['Operate and secure long-range communication arrays', 'Relay orders between command and field units', 'Monitor First Order transmissions for intelligence', 'Maintain backup communication protocols during evacuations'],
                'requirements' => ['Communications or signals experience', 'Encryption and slicing knowledge', 'Composure during evacuations'],
                'perks' => 'Command-center access, porg-free workstation (not guaranteed), camaraderie'],
            ['company' => 'Resistance', 'host' => 'join.resistance.dqr', 'title' => 'Bomber Crew Chief', 'location' => 'Resistance Fleet, Mobile', 'type' => 'Full-time, combat',
                'pay' => '1,300 credits/month plus combat pay',
                'summary' => 'Lead a StarFortress bomber crew against First Order capital ships. Precision, courage, and teamwork are everything.',
                'duties' => ['Command bomber crew during sorties', 'Coordinate payload deployment with squadron leaders', 'Maintain bomber readiness and crew training', 'Conduct post-mission debriefs'],
                'requirements' => ['Combat aviation experience', 'Leadership under fire', 'Willingness to fly slow ships through heavy flak'],
                'perks' => 'Crew family bond, Resistance commendations, the chance to change the galaxy'],
            ['company' => 'Naboo Royal Security Forces', 'host' => 'careers.theed.naboo', 'title' => 'Royal Handmaiden & Security Aide', 'location' => 'Theed Royal Palace, Naboo', 'type' => 'Full-time',
                'pay' => '2,600 credits/month plus palace residence',
                'summary' => 'Protect and support the elected monarch of Naboo. Handmaidens serve as advisors, decoys, and bodyguards — sometimes all in the same afternoon.',
                'duties' => ['Provide close protection for the monarch', 'Serve as decoy during high-risk public appearances', 'Assist with ceremonial and diplomatic duties', 'Train in combat and evasive protocols'],
                'requirements' => ['Security or military training', 'Discretion and poise', 'Ability to wear elaborate formal attire quickly'],
                'perks' => 'Palace living, Naboo lake-country retreats, royal gratitude'],
            ['company' => 'Mon Calamari Shipyards', 'host' => 'careers.dacshipyards.mc', 'title' => 'Capital Ship Designer', 'location' => 'Dac (Mon Cala)', 'type' => 'Full-time',
                'pay' => '5,200 credits/month plus design-award bonuses',
                'summary' => 'Design capital ships with the organic, resilient style that turned Mon Cal cruisers into the backbone of the Rebel fleet. Every hull is unique; every ship is a work of art.',
                'duties' => ['Develop capital-ship designs from concept to blueprint', 'Integrate shield redundancy and hull resilience', 'Collaborate with fleet admirals on tactical requirements', 'Mentor junior designers'],
                'requirements' => ['Naval architecture expertise', 'Portfolio of capital-ship designs', 'Comfort working underwater'],
                'perks' => 'Oceanfront housing, cultural festivals, Admiral Ackbar\'s endorsement'],
            ['company' => 'Canto Bight Casino', 'host' => 'careers.cantobight.cant', 'title' => 'Fathier Racing Stable Manager', 'location' => 'Canto Bight, Cantonica', 'type' => 'Full-time',
                'pay' => '3,000 credits/month plus race-day bonuses',
                'summary' => 'Manage the racing stables at the galaxy\'s most glamorous casino city. You will oversee fathier care, trainers, and stable hands — with a new mandate for humane treatment.',
                'duties' => ['Oversee health and training of racing fathiers', 'Manage stable staff and scheduling', 'Implement humane animal-welfare standards', 'Coordinate with race officials and veterinarians'],
                'requirements' => ['Animal husbandry or stable management experience', 'Commitment to animal welfare', 'Ability to work in a high-stakes environment'],
                'perks' => 'Coastal residence, casino access, meaningful reform work'],
            ['company' => 'Lothal Resistance Cell', 'host' => 'spectres.lothal.org', 'title' => 'Ghost Crew Engineer', 'location' => 'Lothal', 'type' => 'Full-time, covert',
                'pay' => 'Shared crew earnings; credits vary by mission',
                'summary' => 'Keep the Ghost flying and the crew one step ahead of the Empire. You will repair a VCX-100 freighter, modify droids, and occasionally paint murals on Imperial property.',
                'duties' => ['Maintain and upgrade the Ghost and Phantom shuttle', 'Build and repair gear for covert missions', 'Improvise explosives and diversions', 'Support pilots during combat maneuvers'],
                'requirements' => ['Mechanical and electrical engineering skill', 'Artistic streak welcome', 'Tolerance for grumpy astromechs'],
                'perks' => 'Crew family, adventure, your own cabin on the Ghost'],
            ['company' => 'Coruscant Underworld Police', 'host' => 'jobs.coruscantsecurity.gov', 'title' => 'Detective', 'location' => 'Level 1313, Coruscant', 'type' => 'Full-time',
                'pay' => '3,100 credits/month plus undercover pay',
                'summary' => 'Investigate crime in the galaxy\'s deepest urban levels. Level 1313 is dangerous, crowded, and full of cases no one else will take.',
                'duties' => ['Investigate smuggling, theft, and organized crime', 'Develop informant networks in the underworld', 'Collect evidence and testify in court', 'Coordinate with Senate security on high-profile cases'],
                'requirements' => ['Law-enforcement academy graduation', 'Investigative experience', 'Street-level instincts'],
                'perks' => 'Speeder assignment, hazard pay, law-enforcement pension'],
        ];
    }
}
