import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import '../../../css/app.css';
import { ArrowDown, ArrowRight, Bookmark, BriefcaseBusiness, CalendarDays, Check, ChevronRight, Clock, FileText, LayoutDashboard, ListChecks, MapPin, Plus, Search, Settings, Sparkles, Target } from 'lucide-react';
import { Button } from '@/Components/ui/button';
import { Badge } from '@/Components/ui/badge';
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from '@/Components/ui/card';
import { Tabs, TabsList, TabsTrigger } from '@/Components/ui/tabs';
import { Input } from '@/Components/ui/input';
import { Label } from '@/Components/ui/label';
import { Textarea } from '@/Components/ui/textarea';
import { Select } from '@/Components/ui/select';
import { Separator } from '@/Components/ui/separator';
import { Progress } from '@/Components/ui/progress';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '@/Components/ui/dialog';
import { SidebarProvider, Sidebar, SidebarHeader, SidebarContent, SidebarGroup, SidebarGroupLabel, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarFooter, SidebarTrigger } from '@/Components/ui/sidebar';
import { cn } from '@/lib/utils';
import './dashboards.css';

const designs = [
  {name: "Today’s desk", note: 'A practical home for your daily job search.', title: 'Good morning, Jordan.', subtitle: 'A little preparation today. A better opportunity tomorrow.'},
  {name: 'Opportunity explorer', note: 'A discovery-led dashboard for finding the right role.', title: 'Your next chapter starts here.', subtitle: 'Explore opportunities that connect with the work you want to do.'},
  {name: 'Command center', note: 'See every application, its stage, and its next action.', title: 'Your search, in motion.', subtitle: 'Keep opportunities moving without losing the details.'},
  {name: 'Weekly planner', note: 'Organize your search around time and commitments.', title: 'Make room for what’s next.', subtitle: 'Your interviews, preparation, and follow-ups in one week.'},
  {name: 'One next step', note: 'A calm dashboard that gives you one useful place to start.', title: 'You don’t have to do it all today.', subtitle: 'Let’s move one good opportunity forward.'},
];
const initialJobs = [
  {id:1,company:'Meridian',role:'Senior Product Designer',location:'Remote · US',pay:'$150k–$180k',stage:'Preparing',reason:'Complex workflows and design systems align with your product-design resume.',next:'Review your tailored resume',mark:'M',color:'violet'},
  {id:2,company:'Arc Studio',role:'Lead Experience Designer',location:'New York · Hybrid',pay:'$160k–$190k',stage:'Interview',reason:'Your cross-functional leadership experience is relevant to this team.',next:'Prepare for portfolio conversation',mark:'A',color:'terracotta'},
  {id:3,company:'Forma',role:'Product Designer',location:'Remote · US',pay:'$135k–$165k',stage:'Applied',reason:'The role emphasizes accessible interfaces and hands-on prototyping.',next:'Follow up with recruiting',mark:'F',color:'green'},
  {id:4,company:'Orbit',role:'Senior UX Designer',location:'San Francisco · Hybrid',pay:'$145k–$175k',stage:'Saved',reason:'Your onboarding work could support their activation projects.',next:'Choose a base resume',mark:'O',color:'blue'},
  {id:5,company:'Common Ground',role:'Design Systems Designer',location:'Remote · US',pay:'$140k–$170k',stage:'Saved',reason:'Component libraries and accessible interaction patterns are central to the role.',next:'Read the job description',mark:'C',color:'gold'},
];
type Job = typeof initialJobs[number];
const events = [
  {day:'Mon',date:'21',time:'9:30 AM',title:'Tailor Meridian resume',type:'Preparation',company:'Meridian',job:1},
  {day:'Tue',date:'22',time:'11:00 AM',title:'Portfolio conversation',type:'Interview',company:'Arc Studio',job:2},
  {day:'Wed',date:'23',time:'10:00 AM',title:'Follow up with recruiting',type:'Follow-up',company:'Forma',job:3},
  {day:'Thu',date:'24',time:'2:00 PM',title:'Explore saved opportunities',type:'Discovery',company:'Orbit',job:4},
  {day:'Fri',date:'25',time:'9:00 AM',title:'Review your search',type:'Planning',company:'Your workspace',job:5},
];
function App(){
  const [design,setDesign]=useState('0');
  const [jobs,setJobs]=useState(initialJobs);
  const [query,setQuery]=useState('');
  const [remote,setRemote]=useState('all');
  const [selected,setSelected]=useState<Job|null>(null);
  const [completed,setCompleted]=useState<number[]>([]);
  const [notes,setNotes]=useState<Record<number,string>>({});
  const [day,setDay]=useState('Tue');
  const [stage,setStage]=useState('All');
  const [add,setAdd]=useState(false);
  const [company,setCompany]=useState('');
  const [role,setRole]=useState('');
  const [saved,setSaved]=useState<number[]>([]);
  const d=designs[+design];
  const visible=jobs.filter(j => `${j.company} ${j.role}`.toLowerCase().includes(query.toLowerCase()) && (remote==='all'||j.location.startsWith('Remote')) && (stage==='All'||stage===j.stage));
  const open=(j:Job)=>setSelected(j);
  const toggleSave=(id:number)=>setSaved(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
  const count=(name:string)=>jobs.filter(j=>j.stage===name).length;
  const logo=(j:Job)=><span className={`company-mark ${j.color}`} aria-hidden="true">{j.mark}</span>;
  const jobButton=(j:Job)=><Button variant="ghost" size="sm" onClick={()=>open(j)}>Open<ArrowRight/></Button>;
  const resumeLink=<Button variant="outline" asChild><a href="./guidance.html"><FileText/>Open resume workspace</a></Button>;
  const taskRows=<div className="flex flex-col">{jobs.slice(0,3).map((j,i)=><div className="task-row" key={j.id}><Button size="icon" variant={completed.includes(j.id)?'secondary':'outline'} aria-label={`${completed.includes(j.id)?'Reopen':'Complete'} ${j.next}`} onClick={()=>setCompleted(v=>v.includes(j.id)?v.filter(x=>x!==j.id):[...v,j.id])}>{completed.includes(j.id)?<Check/>:<span className="text-xs">{i+1}</span>}</Button><div className="min-w-0 flex-1"><button className={cn('text-left text-sm font-medium hover:underline',completed.includes(j.id)&&'line-through text-muted-foreground')} onClick={()=>open(j)}>{j.next}</button><p className="mt-1 text-xs text-muted-foreground">{j.company} · {i===0?'Resume preparation':i===1?'Tuesday, 11:00 AM':'Wednesday, 10:00 AM'}</p></div><Badge variant="outline">{i===0?'Today':i===1?'Upcoming':'This week'}</Badge></div>)}</div>;
  const resumeCard=<Card className="shadow-none"><CardHeader><CardTitle>Your resume foundation</CardTitle><CardDescription>Choose a base. Tailor a separate copy for each role.</CardDescription></CardHeader><CardContent className="flex flex-col gap-4">{['Product design','Design leadership'].map((r,i)=><div className="flex items-center gap-3" key={r}><FileText className="size-5 text-muted-foreground"/><div className="flex-1"><p className="text-sm font-medium">{r}</p><p className="text-xs text-muted-foreground">{i===0?'Jordan Rivera · Default base':'Jordan Rivera · Leadership base'}</p></div><Badge variant="secondary">Base</Badge></div>)}</CardContent><CardFooter>{resumeLink}</CardFooter></Card>;
  const stats=<div className="stats-strip">{[['Saved',count('Saved')],['Preparing',count('Preparing')],['Applied',count('Applied')],['Interview',count('Interview')]].map(([label,n])=><button key={label} onClick={()=>{setStage(String(label));setDesign('2');}} className="stat-item"><span className="text-xs text-muted-foreground">{label}</span><strong className="text-3xl font-semibold tracking-tight">{n}</strong><span className="text-xs text-muted-foreground">View opportunities ↗</span></button>)}</div>;
  const topActions=<div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>{setDesign('1');setStage('All');}}><Search/>Find a job</Button><Button onClick={()=>setAdd(true)}><Plus/>Add a job</Button></div>;
  return <div className={`dashboard-exploration direction-${design}`}><div className="concept-picker"><div><span className="text-xs font-semibold uppercase tracking-widest">Dashboard studies</span><p className="text-xs text-muted-foreground">Five directions · Fictional sample data</p></div><Tabs value={design} onValueChange={v=>{setDesign(v);setStage('All');setQuery('');}}><TabsList className="h-auto flex-wrap">{designs.map((x,i)=><TabsTrigger value={String(i)} key={x.name}>{i+1}. {x.name}</TabsTrigger>)}</TabsList></Tabs></div><SidebarProvider style={{'--sidebar-width':'13rem'} as React.CSSProperties}>{design!=='1'&&design!=='4'&&<Sidebar className="study-sidebar"><SidebarHeader className="p-5"><span className="text-lg font-semibold tracking-tight">Resumegen<span className="text-muted-foreground">.</span></span></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupLabel>Workspace</SidebarGroupLabel><SidebarMenu>{[[LayoutDashboard,'Overview'],[BriefcaseBusiness,'Find jobs'],[ListChecks,'Applications'],[FileText,'Resumes']].map(([Icon,label])=>{const Glyph=Icon as typeof FileText;return <SidebarMenuItem key={String(label)}><SidebarMenuButton isActive={label==='Overview'} onClick={()=>label==='Find jobs'?(setDesign('1'),setStage('All')):label==='Applications'?(setDesign('2'),setStage('All')):label==='Resumes'?setSelected({...jobs[0],role:'Your resume library',next:'Open your base and tailored resumes'}):setDesign('0')}><Glyph/><span>{String(label)}</span></SidebarMenuButton></SidebarMenuItem>;})}</SidebarMenu></SidebarGroup><SidebarGroup><SidebarGroupLabel>Your focus</SidebarGroupLabel><p className="px-2 text-sm leading-6 text-muted-foreground">Product design<br/>Remote & hybrid<br/>Senior & lead roles</p></SidebarGroup></SidebarContent><SidebarFooter className="p-5"><span className="text-sm font-medium">Jordan Rivera</span><span className="text-xs text-muted-foreground">Your search, your pace.</span></SidebarFooter></Sidebar>}<main className="min-w-0 flex-1">{(design==='1'||design==='4')?<nav className="top-navigation"><span className="text-xl font-semibold tracking-tight">Resumegen.</span><div className="flex flex-wrap gap-2"><Button variant="ghost" onClick={()=>setDesign('0')}>Overview</Button><Button variant="ghost" onClick={()=>setDesign('1')}>Find jobs</Button><Button variant="ghost" onClick={()=>setDesign('2')}>Applications</Button><Button variant="outline" asChild><a href="./guidance.html">My resumes</a></Button></div><Badge variant="secondary">Jordan Rivera</Badge></nav>:<div className="workspace-top"><div className="flex items-center gap-2"><SidebarTrigger/><span className="text-sm text-muted-foreground">Workspace / Overview</span></div><Badge variant="outline">September 2026 · Sample week</Badge></div>}
  <div className="dashboard-content"><header className="dashboard-heading"><div><p className="eyebrow">{d.note}</p><h1>{d.title}</h1><p className="text-muted-foreground">{d.subtitle}</p></div>{design!=='4'&&topActions}</header>
  {design==='0'&&<><div className="grid gap-6 lg:grid-cols-[minmax(0,1.5fr)_minmax(300px,1fr)]"><div className="flex flex-col gap-6"><section className="feature-panel"><Badge variant="outline">Pick up where you left off</Badge><h2 className="mt-5 text-2xl font-semibold">A stronger application<br/>for Meridian.</h2><p className="mt-3 max-w-md text-sm leading-6 text-muted-foreground">Your tailored resume is ready for a final look. Review the details, then apply on the employer’s website.</p><div className="mt-6 flex flex-wrap items-center gap-4"><Button onClick={()=>open(jobs[0])}>Continue preparation<ArrowRight/></Button><span className="text-xs text-muted-foreground">Base resume stays unchanged</span></div></section><Card className="shadow-none"><CardHeader><div className="flex items-center justify-between"><CardTitle>Your next moves</CardTitle><Badge variant="secondary">{completed.length} of 3 complete</Badge></div></CardHeader><CardContent>{taskRows}</CardContent></Card></div><div className="flex flex-col gap-6"><Card className="shadow-none"><CardHeader><div className="flex items-center gap-2 text-sm text-muted-foreground"><CalendarDays className="size-4"/>Coming up next</div><CardTitle>Portfolio conversation</CardTitle><CardDescription>Arc Studio · Lead Experience Designer</CardDescription></CardHeader><CardContent><div className="calendar-ticket"><strong>22</strong><div>Tuesday, September<br/><span className="text-muted-foreground">11:00 AM · 45 minutes</span></div></div></CardContent><CardFooter><Button variant="outline" onClick={()=>open(jobs[1])}>Open interview notes<ArrowRight/></Button></CardFooter></Card>{resumeCard}</div></div>{stats}</>}
  {design==='1'&&<><div className="search-bar"><Search className="size-5 text-muted-foreground"/><Input className="flex-1" aria-label="Search opportunities" placeholder="Search roles or companies…" value={query} onChange={e=>setQuery(e.target.value)}/><Select aria-label="Work location" value={remote} onChange={e=>setRemote(e.target.value)}><option value="all">All locations</option><option value="remote">Remote only</option></Select></div><div className="discovery-layout"><section className="discovery-intro"><span className="eyebrow">A direction worth exploring</span><h2>Find work<br/>that fits<br/><em>your strengths.</em></h2><p className="text-sm leading-7 text-muted-foreground">Start with a promising role. Bring your own experience. Build an application that connects the two.</p><Separator/><p className="text-xs leading-6 text-muted-foreground">Why these roles? The examples below relate job requirements to your product-design background. These are sample explanations, not calculated match scores.</p><Badge variant="outline" className="self-start">{saved.length} bookmarked this session</Badge></section><div><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-semibold">Opportunities to explore</h2><span className="text-sm text-muted-foreground">{visible.length} roles</span></div><div className="grid gap-4 xl:grid-cols-2">{visible.map(j=><Card className="shadow-none" key={j.id}><CardHeader><div className="flex items-center justify-between">{logo(j)}<Button variant="ghost" size="icon" aria-label={`${saved.includes(j.id)?'Unsave':'Save'} ${j.company}`} onClick={()=>toggleSave(j.id)}><Bookmark fill={saved.includes(j.id)?'currentColor':'none'}/></Button></div><CardTitle className="mt-3">{j.role}</CardTitle><CardDescription>{j.company} · {j.location}</CardDescription></CardHeader><CardContent className="flex flex-col gap-4"><span className="text-sm font-medium">{j.pay}</span><p className="text-sm leading-6 text-muted-foreground">{j.reason}</p></CardContent><CardFooter className="justify-between"><Badge variant="outline">{j.stage}</Badge><Button variant="outline" onClick={()=>open(j)}>Explore role<ArrowRight/></Button></CardFooter></Card>)}</div>{visible.length===0&&<p role="status" className="py-12 text-muted-foreground">No sample roles match. Try another search or location.</p>}</div></div></>}
  {design==='2'&&<>{stats}<div className="flex flex-wrap items-center justify-between gap-3"><Tabs value={stage} onValueChange={setStage}><TabsList className="h-auto flex-wrap">{['All','Saved','Preparing','Applied','Interview'].map(s=><TabsTrigger key={s} value={s}>{s}</TabsTrigger>)}</TabsList></Tabs><Input aria-label="Filter applications" className="max-w-xs" placeholder="Filter companies or roles…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="pipeline-grid">{['Saved','Preparing','Applied','Interview'].filter(s=>stage==='All'||stage===s).map(s=><section key={s} className="pipeline-column"><div className="mb-4 flex items-center justify-between"><h2 className="text-sm font-semibold">{s}</h2><Badge variant="secondary">{visible.filter(j=>j.stage===s).length}</Badge></div>{visible.filter(j=>j.stage===s).map(j=><Card className="mb-3 shadow-none" key={j.id}><CardHeader><div className="flex items-center gap-3">{logo(j)}<span className="text-sm font-medium">{j.company}</span></div><CardTitle className="mt-3">{j.role}</CardTitle><CardDescription>{j.location}</CardDescription></CardHeader><CardContent><p className="text-xs text-muted-foreground">NEXT ACTION</p><p className="mt-2 text-sm leading-6">{j.next}</p></CardContent><CardFooter className="justify-between"><Badge variant="outline">{j.id===2?'Sep 22':j.id===3?'Sep 23':'Ready to work'}</Badge>{jobButton(j)}</CardFooter></Card>)}</section>)}</div><div className="flex items-center gap-3 rounded-lg border p-4"><ListChecks className="size-5 text-muted-foreground"/><p className="text-sm text-muted-foreground">Preparation and submission stay separate. You submit on the employer’s site, then update your tracker.</p></div></>}
  {design==='3'&&<><div className="planner-heading"><div><h2 className="text-xl font-semibold">September 21–25</h2><p className="text-sm text-muted-foreground">A manageable week, with room to prepare.</p></div><Badge variant="outline">{events.length} planned activities</Badge></div><div className="week-grid">{events.map(e=><button className={cn('day-cell',day===e.day&&'selected-day')} key={e.day} onClick={()=>setDay(e.day)}><span className="text-sm text-muted-foreground">{e.day}</span><strong className="text-3xl font-medium">{e.date}</strong><span className="mt-5 text-xs text-muted-foreground">{e.time}</span><span className="mt-2 text-sm font-semibold">{e.title}</span><span className="mt-2 text-xs text-muted-foreground">{e.company}</span><span className="mt-auto pt-5"><Badge variant={e.type==='Interview'?'default':'secondary'}>{e.type}</Badge></span></button>)}</div><div className="grid gap-6 lg:grid-cols-[minmax(0,1.3fr)_minmax(300px,1fr)]"><Card className="shadow-none"><CardHeader><CardTitle>{day} · Make the time count</CardTitle><CardDescription>Everything you need for the selected activity.</CardDescription></CardHeader><CardContent>{events.filter(e=>e.day===day).map(e=><div key={e.day} className="flex flex-col gap-4"><div className="flex items-center gap-3"><Clock className="size-5"/><h3 className="text-lg font-medium">{e.title}</h3></div><p className="text-sm text-muted-foreground">{e.company} · {e.time}</p><Label htmlFor="planner-note">Preparation notes</Label><Textarea id="planner-note" placeholder="What do you want to cover?" value={notes[e.job]||''} onChange={x=>setNotes(n=>({...n,[e.job]:x.target.value}))}/><Button className="self-start" onClick={()=>open(jobs.find(j=>j.id===e.job)!)}>Open related opportunity<ArrowRight/></Button></div>)}</CardContent></Card><Card className="shadow-none"><CardHeader><CardTitle>A few things to move forward</CardTitle><CardDescription>Small tasks, clear outcomes.</CardDescription></CardHeader><CardContent>{taskRows}</CardContent></Card></div></>}
  {design==='4'&&<><div className="focus-layout"><section className="focus-main"><div className="flex items-center gap-2 text-sm text-muted-foreground"><Target className="size-4"/>YOUR NEXT STEP</div><h2>Turn your experience<br/>into a strong<br/><span>Meridian application.</span></h2><p className="max-w-lg text-base leading-7 text-muted-foreground">You’ve chosen the role and created a tailored copy. Now review your resume, make it your own, and take the next step when you’re ready.</p><div className="mt-8 flex flex-wrap gap-3"><Button size="lg" onClick={()=>open(jobs[0])}>Continue my application<ArrowRight/></Button><Button size="lg" variant="ghost" onClick={()=>setDesign('1')}>Explore other roles</Button></div><div className="mt-10 flex flex-col gap-3"><div className="flex justify-between text-xs text-muted-foreground"><span>Preparation journey</span><span>Step 3 of 4</span></div><Progress value={75}/><div className="flex flex-wrap justify-between gap-2 text-xs"><span>✓ Choose role</span><span>✓ Create copy</span><strong>Review resume</strong><span className="text-muted-foreground">Apply yourself</span></div></div></section><aside className="focus-aside"><p className="eyebrow">Also on your horizon</p><div className="flex items-start gap-4"><div className="date-block">TUE<strong>22</strong></div><div><h3 className="font-semibold">Meet Arc Studio</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Portfolio conversation<br/>11:00 AM · 45 minutes</p><Button variant="link" className="px-0" onClick={()=>open(jobs[1])}>Prepare for the conversation<ArrowRight/></Button></div></div><Separator/><div><h3 className="font-semibold">Your search is taking shape.</h3><div className="mt-5 grid grid-cols-2 gap-5"><div><strong className="text-3xl">{jobs.length}</strong><p className="text-xs text-muted-foreground">opportunities tracked</p></div><div><strong className="text-3xl">{count('Interview')}</strong><p className="text-xs text-muted-foreground">conversation ahead</p></div></div></div><Separator/>{resumeLink}</aside></div><div className="focus-footer"><p className="text-sm text-muted-foreground">A good application tells your story clearly. Take the time you need.</p><Button variant="ghost" onClick={()=>setDesign('2')}>See my full search<ArrowRight/></Button></div></>}
  </div></main></SidebarProvider><Dialog open={!!selected} onOpenChange={v=>!v&&setSelected(null)}><DialogContent><DialogHeader><DialogTitle>{selected?.role}</DialogTitle><DialogDescription>{selected?.company} · {selected?.location}</DialogDescription></DialogHeader>{selected&&<div className="flex flex-col gap-4"><Badge variant="secondary" className="self-start">{selected.stage}</Badge><p className="text-sm leading-6">{selected.reason}</p><Separator/><h3 className="font-medium">Next: {selected.next}</h3><Label htmlFor="opportunity-note">Opportunity notes</Label><Textarea id="opportunity-note" value={notes[selected.id]||''} onChange={e=>setNotes(v=>({...v,[selected.id]:e.target.value}))} placeholder="Questions, talking points, and follow-up details…"/><p className="text-xs text-muted-foreground">Interactive mockup. Notes stay in this browser session. No real application is submitted.</p></div>}<DialogFooter><Button variant="outline" onClick={()=>setSelected(null)}>Done</Button><Button asChild><a href="./guidance.html">Open sample resume editor<ArrowRight/></a></Button></DialogFooter></DialogContent></Dialog><Dialog open={add} onOpenChange={setAdd}><DialogContent><DialogHeader><DialogTitle>Add a sample opportunity</DialogTitle><DialogDescription>Try how a manually entered job joins your dashboard.</DialogDescription></DialogHeader><Label htmlFor="new-company">Company</Label><Input id="new-company" value={company} onChange={e=>setCompany(e.target.value)}/><Label htmlFor="new-role">Role</Label><Input id="new-role" value={role} onChange={e=>setRole(e.target.value)}/><DialogFooter><Button variant="outline" onClick={()=>setAdd(false)}>Cancel</Button><Button disabled={!company.trim()||!role.trim()} onClick={()=>{setJobs(v=>[...v,{...initialJobs[3],id:Math.max(...v.map(j=>j.id))+1,company:company.trim(),role:role.trim(),mark:company.trim()[0].toUpperCase(),location:'Location not specified',pay:'Salary not specified',reason:'Added manually in this preview. Read the job description before tailoring.',next:'Add the job description'}]);setCompany('');setRole('');setAdd(false);setDesign('2');setStage('Saved');}}>Add to saved</Button></DialogFooter></DialogContent></Dialog></div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
